### ISSUE TITLE
remove extra text on home page

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#107]
Remove the extra text "one" showing between rich text and faculty picker on the very left...
![Screen Shot 2021-05-25 at 4 21 44 PM](https://user-images.githubusercontent.com/54747669/119570193-68159400-bd75-11eb-89b9-e2f721550846.png)

**Comment by robgasc** [comment]
Hey Melissa, I looked at this and it seems the text itself might be in the editor. I don't have perms to the ansc site else I'd take a closer look.

**Comment by mwllr** [comment]
has been removed either by changing to a formatted paragraph for stripped out of faculty explorer....
