### ISSUE TITLE
Contact Info Paragraph

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#146]
![image](https://user-images.githubusercontent.com/1544079/120853885-efb38d80-c541-11eb-99e7-4b140e504cd4.png)

**Comment by mwllr** [comment]
Add field for spacing before paragraph: no, small, med, lg, xlg..
See Call to Action Narrow for example already added.

**Comment by mwllr** [comment]
TESTING (if you can give example page and screen shots, please do so!):
Share your feedback in a new comment and check off the part you have done in this comment:
- [ ] Usability - front end (how does this behave/display?)
- [ ] Usability - back end (intuitive? easy/hard to use?)
- [ ] Accessibility - (FAE site/run on pages with these paragraph types)

Browser Testing (Please be descriptive in browsers you tested on platform and version #.)
- [ ] Mobile - iphone
- [ ] Mobile - android
- [ ] Edge 
- [ ] Safari
- [ ] Chrome
- [ ] Firefox

**Comment by mwllr** [comment]
Need to add titles to section - in the back end, but not displaying.  centered over section. same as h2 for site overall. 
Should look like: 
![Screen Shot 2021-07-09 at 6 25 44 PM](https://user-images.githubusercontent.com/54747669/125144365-42eda280-e0e3-11eb-8717-e29565b9c9c9.png)
Also, please match the spacing for the title, job, address. 
The name should only be 28px.

**Comment by lizshalley** [comment]
change image size to 250 x 333px. Right now I get a minimum size upload of 500 x 500.

**Comment by wrg20** [comment]
250 max width...instead of 350px for portrait view for now.

**Comment by lizshalley** [comment]
Email field doesn't link to email address.

**Comment by wrg20** [comment]
Contact content type issue: when image is left and text is right, image overlaps onto right side. But when image is right and text is left, it's fine. Example: https://staging.ansc.illinois.edu/about/facilities/dixon-springs-agricultural-center

Minimum photo dimensions are set to 500 x 500 so I had adjust this image to fit those parameters

**Comment by mwllr** [comment]
- [x] change button color to blue on the gray background
- [x] photos should stack on tablet/mobile
- [x] section title not showing - in backend, just not showing. should match orange h2.
- [x] make image size 250 max width...instead of 350px for portrait view for now.
- [x] when showing next to side nav, they overlap.
![Screen Shot 2021-08-09 at 3 32 58 PM](https://user-images.githubusercontent.com/54747669/128770598-5917afe3-c0b7-4828-ae41-a4293f048973.png)

**Comment by lizshalley** [comment]
![Screen Shot 2021-08-12 at 3 58 31 PM](https://user-images.githubusercontent.com/8646013/129269040-90a90c80-a5d2-4530-8389-cd60e44db656.png)

**Comment by wrg20** [comment]
![image](https://user-images.githubusercontent.com/1544079/130280285-17a334f4-df86-4f48-b806-208590a3a084.png)
buttons work as intended....the button text should be pulled out of the Address area and input into the button fields.

**Comment by wrg20** [comment]
alright some of these are ready for review on staging.ansc.illinois.edu

**Comment by wrg20** [comment]
Merge #386

**Comment by mwllr** [comment]
@wrg20 
photos still need to be left/right, not centered on desktop version (even with side nav). could also do 1/3 and 2/3 instead of 50/50 for columns next to side nav. 
We will need to break quicker for side nav to diappear. That will come on another request.
