### ISSUE TITLE
fix header font weights

### ISSUE THREAD

**Issue by lizshalley** [ATLAS-Illinois/Illinois-Framework-Theme#147]
h3 and h4 are heavier weight than h2 and should be the same.

![Screen Shot 2021-06-07 at 12 46 09 PM](https://user-images.githubusercontent.com/8646013/121065734-b7ed5580-c78e-11eb-9d01-3dc5f15a3e0c.png)

![Screen Shot 2021-06-07 at 12 46 01 PM](https://user-images.githubusercontent.com/8646013/121065822-cdfb1600-c78e-11eb-9e61-0d7b7bc1d2aa.png)

**Comment by mwllr** [comment]
@lizshalley  - these will come from the components. - see https://cdn.brand.illinois.edu/toolkit/2.0/examples/stylesheets/formatting/index.html
Do we need to change those?? I think they look good.

**Comment by lizshalley** [comment]
@mwllr woops, sorry, didn't realize that. thanks ,they look good in the link.
