### ISSUE TITLE
Table Styling in Body/rich Text, etc....

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#148]
@lizshalley  - Add your styling here for the tables please.

**Comment by lizshalley** [comment]
zpl.io/bLq5d9d
zpl://screen?pid=608186933d2d341c92c71926&sid=60bfd6fb933740becbdc9c84

**Comment by lizshalley** [comment]
@wrg20 Matt is going to work on this in the toolkit.

**Comment by mwllr** [comment]
@lizshalley -did this get added/is it done? If so, move to melissa double check column.

**Comment by nbaxley-uiuc** [comment]
Here's a sample page on the sandbox with table content.  Currently it doesn't look right.  https://drupal-sandbox.webtheme.illinois.edu/table-example
