### ISSUE TITLE
Icon row paragraph

### ISSUE THREAD

**Issue by magjarvis** [ATLAS-Illinois/Illinois-Framework-Theme#149]
- [x] Altgeld text for callout on gray background
- [x] 60 px padding inside top of paragraph total
- [x] 75 px padding inside bottom of paragraph total
- [x] vertical spacing between title and icons should be 20 px.
- [x] on mobile - need more vertical spacing between each icon set + 10px
- [x] need wrapping on tablet and desktop
- [x] Database backend: Remove Alignment option - Title should only center, remove option for text align left.
- [x] Database backend: Remove Spacing above paragraph

**Comment by mwllr** [comment]
Add field for spacing before paragraph: no, small, med, lg, xlg..
See Call to Action Narrow for example already added.

**Comment by mwllr** [comment]
- [ ] mobile stacking of icons need more space between icons.

![Screen Shot 2021-07-09 at 3 28 25 PM](https://user-images.githubusercontent.com/54747669/125132871-930c3b00-e0ca-11eb-8c0c-2e13e2f7fdc2.png)

**Comment by mwllr** [comment]
- [ ] Need white callout text on the gray background. Orange text works on white and gray backgrounds.
- [ ] set margins to max out at 1200.
- [ ] stacking should occur when we have more than 5 or so icons... see: https://staging.ansc.illinois.edu/testing/test-icon-row

**Comment by mwllr** [comment]
Need to see white on gray, then look at link of text color on gray background. Is the med blue okay? do we want something different?
![Screen Shot 2021-07-09 at 3 43 58 PM](https://user-images.githubusercontent.com/54747669/125134131-8daff000-e0cc-11eb-9eb7-f4ded7886e6b.png)

**Comment by wrg20** [comment]
Wrapping of icons can be done by changing these rules on these classes.

![image](https://user-images.githubusercontent.com/1544079/125136403-5fccaa80-e0d0-11eb-9acf-0526502abec2.png)

![image](https://user-images.githubusercontent.com/1544079/125136415-6529f500-e0d0-11eb-8eef-86ad55f3b0bd.png)

**Comment by lizshalley** [comment]
add FAQ icon: [https://toolkit.marketing.web.illinois.edu/icons/
![Screen Shot 2021-07-12 at 11 05 02 AM](https://user-images.githubusercontent.com/8646013/125320206-17e09a00-e301-11eb-851d-32fd5b649ad4.png)
](url)

**Comment by magjarvis** [comment]
![icon-wrap](https://user-images.githubusercontent.com/8452264/125979373-b466077d-1c45-4920-a1e9-26d8a0689419.png)
this is how 7 icons are wrapping if we add flex-wrap, 6 icons wrap to three rows of two. is that what we still want to do? Or should we limit the number of icons per paragraph?

**Comment by lizshalley** [comment]
my vote would be to limit to 5, @mwllr?

**Comment by magjarvis** [comment]
White text on gray background fails all accessibility checks for contrast. We could do illini blue callout text? Or Altgeld orange passes AA standards for the callout text if we want to use that. 
![icon-blue](https://user-images.githubusercontent.com/8452264/125979963-aea11820-1f99-4cf8-ba97-b50d8b9293ef.png)

**Comment by magjarvis** [comment]
![icons-altgeld](https://user-images.githubusercontent.com/8452264/125980062-9f664bd3-c404-429e-bb20-b16417c31aff.png)
Altgeld callout text

**Comment by magjarvis** [comment]
> my vote would be to limit to 5, @mwllr?

![icon-2rows](https://user-images.githubusercontent.com/8452264/125980678-76118887-4e3f-475d-88e4-173f7611da31.png)

So, here is two separate icon row paragraphs on top of each other. top row 5, bottom row 2. With this option you also have the additional option of adding spacing between the two rows

**Comment by magjarvis** [comment]
Obviously, it would look better to do 4 on top of 3, but it would be up to the user, so we might end up with something like the above

**Comment by lizshalley** [comment]
I was thinking 5 max... as in no more than 5 total items per paragraph type. that's probably a design group or @mwllr decision.

**Comment by mwllr** [comment]
- [x] Altgeld text for callout on gray background
- [x] 60 px padding inside top of paragraph
- [x] 75 px padding inside bottom of paragraph
- [x] spacing between title and icons should be 20 px.
- [x] on mobile - need more vertical spacing between each icon set + 10px
- [x] need wrapping on tablet and desktop
- [x] Database backend: Title should only center, remove option for text align left.
- [x] Database backend: Remove Spacing above paragraph

**Comment by mwllr** [comment]
@magjarvis  - ready for you to work some magic!

**Comment by wrg20** [comment]
Add switch / case, for icon row classes and flex-box.

**Comment by trubach** [comment]
@wrg20, @mwllr - I just merged #421 from Maggie. Can you use the sandbox site to verify everything is OK and close this issue if it is? The sandbox won't reflect these changes until tomorrow (9/25). Otherwise, maybe add some more tasks to the list of checkboxes above.

**Comment by mwllr** [comment]
Awesome job Maggie! I believe we are good to go!
