### ISSUE TITLE
Galleria for Flickr Galleries

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#156]
Add in Galleria for flickr galleries.
We will use the folio one for the animal sciences web galleries. 
@lizshalley - please put each gallery link here for Bill for the facilities pages and anywhere else we may need one.

Thanks.

**Comment by lizshalley** [comment]
[Meat Science gallery](https://www.flickr.com/photos/153584475@N06/51179312039/in/album-72157719184125316) > [goes here](https://staging.ansc.illinois.edu/research-outreach/animal-sciences-facilities/meat-science-lab)
[Grein gallery](https://www.flickr.com/photos/153584475@N06/51179299329/in/album-72157719178239303) > [goes here](https://staging.ansc.illinois.edu/research-outreach/animal-sciences-facilities/grein-swine-unit)
[Swine Research Center gallery](https://www.flickr.com/photos/153584475@N06/51177848727/in/album-72157719178344198) > [goes here](https://staging.ansc.illinois.edu/research-outreach/animal-sciences-facilities/swine-research-center)
[Imported Swine gallery](https://www.flickr.com/photos/153584475@N06/51179604345/in/album-72157719178267738) > [goes here](https://staging.ansc.illinois.edu/research-outreach/animal-sciences-facilities/isrl)
[PNCL gallery](https://www.flickr.com/photos/153584475@N06/51179321419/in/album-72157719184157596) > [goes here](https://staging.ansc.illinois.edu/research-outreach/animal-sciences-facilities/pncl)
[Poultry gallery](https://www.flickr.com/photos/153584475@N06/51179324599/in/album-72157719233553730) > [goes here](https://staging.ansc.illinois.edu/research-outreach/animal-sciences-facilities/poulty-research-farm)
[Horse Farm gallery](https://www.flickr.com/photos/153584475@N06/51179602400/in/album-72157719180257499) > [goes here](https://staging.ansc.illinois.edu/research-outreach/animal-sciences-facilities/horse-farm)
[Nutritional Field Lab gallery](https://www.flickr.com/photos/153584475@N06/51178520581/in/album-72157719233520745) > [goes here](https://staging.ansc.illinois.edu/research-outreach/animal-sciences-facilities/nutritional-field-laboratory)
[Lincoln Avenue Dairy gallery](https://www.flickr.com/photos/153584475@N06/51179607655/in/album-72157719180278959)>  [goes here](https://staging.ansc.illinois.edu/research-outreach/animal-sciences-facilities/lincoln-avenue-dairy)
[Orr Beef gallery](https://www.flickr.com/photos/153584475@N06/51178523336/in/album-72157719180307499) > [goes here](https://staging.ansc.illinois.edu/research-outreach/animal-sciences-facilities/orr-beef-research-center)
[Beef and Sheep Research gallery](https://www.flickr.com/photos/153584475@N06/51178713428/in/album-72157719190964477) > [goes here](https://staging.ansc.illinois.edu/research-outreach/animal-sciences-facilities/beef-sheep-lab)
[Feed Technology Center gallery](https://www.flickr.com/photos/153584475@N06/50662834233/in/album-72157717099543448) > [goes here](https://staging.ansc.illinois.edu/research-outreach/animal-sciences-facilities/ftc)
[Dixon Springs gallery](https://www.flickr.com/photos/153584475@N06/albums/72157719184050926) > [goes here](https://staging.ansc.illinois.edu/research-outreach/animal-sciences-facilities/dixon-springs-ag-center)

**Comment by wrg20** [comment]
OK.  I have galleria installed.  They will need to be placed via blocks and it's manual process that requires a developer at this point.   So you'll need to tell me what pages to place each gallery @lizshalley and @mwllr

**Comment by wrg20** [comment]
The flickr integration will require people to create a flickr account and pull an API key unless we can let the whole University use our API key.  I don't know.

**Comment by lizshalley** [comment]
@wrg20 ^^^ updated!

**Comment by mwllr** [comment]
Add in the ability to have a title within the paragraph type. Use h2 styling of site overall.

**Comment by mwllr** [comment]
- [ ] Add in the ability to have a title within the paragraph type. Use h2 styling of site overall.
- [ ] Add ability for title to be left or centered.

**Comment by NotThatDavidCross** [comment]
@mwllr Title just needed to be added to the paragraph to display, but it doesn't have the left/centered option yet.  It will probably need spacing/styling adjustments.  I've added it to FTC on staging: http://staging.ansc.illinois.edu/about/facilities/feed-technology-center

**Comment by mwllr** [comment]
- [ ] Add title center/left option
- [ ] add spacing before title (60px total inside gray background)
- [ ] remove spacing after title, before images start. (35px)
- [ ] 75 px padding at bottom
- [ ] align image to left with text title. off 5-10px?

Currently looks like:
![Screen Shot 2021-08-23 at 10 22 39 AM](https://user-images.githubusercontent.com/54747669/130474733-d2c7b283-79f7-4b9c-a8eb-e43b7815266e.png)

Should look like:
![Screen Shot 2021-08-23 at 10 26 57 AM](https://user-images.githubusercontent.com/54747669/130474740-379e53d4-e3f2-493c-8bef-41dcffd662ec.png)

**Comment by mwllr** [comment]
closing this and moving to ACES as needed for Galleria issues.
