### ISSUE TITLE
Grouped Feature

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#157]
![image](https://user-images.githubusercontent.com/1544079/122971469-b3ab6580-d354-11eb-9c2e-89ef748337b7.png)

**Comment by wrg20** [comment]
Remove fingerprint, callout and tagline fields

**Comment by wrg20** [comment]
backend: move buttons above body, move body above photos

**Comment by wrg20** [comment]
OK.  Made all of those changes for the import

**Comment by lizshalley** [comment]
Make both buttons orange with white hover state. blue ghost button looks like it's disabled.

**Comment by mwllr** [comment]
- [ ] move images back up 
- [ ] align with page title on left

**Comment by mwllr** [comment]
good for now.
![Screen Shot 2021-08-18 at 1 57 54 PM](https://user-images.githubusercontent.com/54747669/129956233-e436c1d7-26c3-44ac-b438-290e0a787139.png)
