### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#178]
Page title next to block I doesn't have the correct font weight coming through.
![Screen Shot 2021-07-12 at 4 35 47 PM](https://user-images.githubusercontent.com/54747669/125359024-52f9c200-e32f-11eb-98f0-7119739ea370.png)

**Comment by wrg20** [comment]
the toolkit had a last-child rule and we had put in our notification script div as the last child so the font weight wasn't being applied...I removed the script from the header and added it just after.
