### ISSUE TITLE
Page Titles

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#183]
{page title} | {college} | UIUC

Example: About Us | College of Agricultural, Consumer and Environmental Sciences | UIUC

**Comment by wrg20** [comment]
@mwllr - right now we have the Page Title | Site Name | University of Illinois - Not all sites will have an associated college but they will all have a site name

![image](https://user-images.githubusercontent.com/1544079/126846295-e718da4b-0ec6-4cb8-b57d-642d1dbec8c3.png)

**Comment by wrg20** [comment]
<title>{{ head_title|safe_join(' | ') }} :: University of Illinois</title>  in the html.html.twig file

 * - head_title: List of text elements that make up the head_title variable.
 *

**Comment by mwllr** [comment]
Can we remove the :: before University of Illinois and change to UIUC

should be:  {page title} | {college} | UIUC
Example: Welcome to Animal Sciences | Animal Sciences | UIUC

**Comment by wrg20** [comment]
The pages have been updated with | UIUC
