### ISSUE TITLE
Adjust column widths with side navigation

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#246]
Adjust the columns so they start at medium down to small

**Comment by wrg20** [comment]
Adjustments made with pull request #250

**Comment by wrg20** [comment]
The proposed adjustment didn't work as planned...need to figure out a different method.

**Comment by mwllr** [comment]
@wrg20 I believe this is done overall or do you still have single instances to finish up?

**Comment by wrg20** [comment]
Merge #386 finished this up when I removed the offset rules in the JS file.
