### ISSUE TITLE
move title on side navigation pages

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#258]
Move the title to the content section of the page if the side navigation is present.
![image](https://user-images.githubusercontent.com/1544079/127930128-24600d22-4d62-4cb3-a282-33570110d0bb.png)

**Comment by wrg20** [comment]
This has been completed but is waiting on a render issue with the directory javascript that dave is fixing now.

**Comment by wrg20** [comment]
should be working now please review @mwllr

**Comment by mwllr** [comment]
Looks good on regular pages and such. Will need to tweak a few special paragraphs like the feature grouped.... done for launch.
![Screen Shot 2021-08-10 at 3 49 50 PM](https://user-images.githubusercontent.com/54747669/128939044-d457de89-1dad-4038-a161-31500ebfc4cd.png)
