### ISSUE TITLE
Fixed Width Overwriting width

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#263]
![image](https://user-images.githubusercontent.com/1544079/128127032-1fc7fdf1-0d34-4d66-9a6c-c78f51589a43.png)
![image](https://user-images.githubusercontent.com/1544079/128127062-4ab675ca-334d-4d4d-bd3c-7138bd48b2db.png)

**Comment by mwllr** [comment]
Looks marvelous!
![Screen Shot 2021-08-04 at 4 27 22 PM](https://user-images.githubusercontent.com/54747669/128257193-15c1b898-7ce4-4651-a912-f8100891c1d8.png)
