### ISSUE TITLE
Hero Paragraph

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#267]
![image](https://user-images.githubusercontent.com/1544079/128244040-28d4e3ac-9daa-445a-838a-52a0b22fc405.png)
![image](https://user-images.githubusercontent.com/1544079/128244087-8e6fe898-297a-4b8a-8dd7-36122677b6d0.png)

**Comment by mwllr** [comment]
- [x] remove space below nav before hero. should butt up to each other....

**Comment by mwllr** [comment]
Looks great for what we can do to launch.
![Screen Shot 2021-08-10 at 4 42 35 PM](https://user-images.githubusercontent.com/54747669/128938957-811611e7-9075-4ae0-969a-b8970a702159.png)
