### ISSUE TITLE
Search functionality & styling

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#271]
Add search for ANSC

**Comment by wrg20** [comment]
@lizshalley - we will need to style the search results page (colors, font, etc). @mwllr - the aces website looks like we used orange and gray.

**Comment by nbaxley-uiuc** [comment]
This ticket is really about STYLING search, @mwllr correct?  Here are several examples of styling from around campus.  Has the design group come up with anything and if not is it worth our time changing things now?

- [ANSC](https://ansc.illinois.edu/search/node?query=Simple) (Drupal framework currentdefault)
- [ACES](https://aces.illinois.edu/search/node?query=Simple)
- [ECE](https://ece.illinois.edu/search?q=Simple)
- [LAS](https://las.illinois.edu/search?qt=Simple)
- [GIES](https://giesbusiness.illinois.edu/search-results/?searchQuery=Simple)
- [Campus](https://illinois.edu/resources/search.html?search=&search_type=all&cx=006549799505564222509%3A-8lddip9q2g&cof=FORID%3A11&q=Simple&sa=Search+Website)
