### ISSUE TITLE
Test Giving with UIF

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#273]

**Comment by mwllr** [comment]
@NotThatDavidCross - I put in 2 new funds and removed 3 funds from showing on the giving page. Do we need to double check that with UIF?
M

**Comment by mwllr** [comment]
Marla said:     You can put a 11 in front but really the actual fund number is just 6 digits

**Comment by NotThatDavidCross** [comment]
Page is published but not linked to.  UIF is reviewing it.  https://ansc.illinois.edu/give
