### ISSUE TITLE
Emeritus Faculty Members

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#319]
- [x] Should be able to get 3-4 people on a line instead of 2.
- [x] Shouldn't be seeing the blue titles with orange under for each person. styling not coming through.
![Screen Shot 2021-08-09 at 4 31 22 PM](https://user-images.githubusercontent.com/54747669/128777198-2ba57a1f-bdab-4a5b-add9-fb590e16dce1.png)

**Comment by lizshalley** [comment]
Looks great! There's one image that seems to be cropped short though in the first row.

**Comment by lizshalley** [comment]
Looks great!

**Comment by mwllr** [comment]
looks great.
@lizshalley -that's what they uploaded in my.aces...
![Screen Shot 2021-08-10 at 9 26 48 AM](https://user-images.githubusercontent.com/54747669/128884969-9673118b-ec9e-4392-847c-9e20d711690e.png)

**Comment by mwllr** [comment]
extra spacing of h3???? remove.
![Screen Shot 2021-08-10 at 9 27 49 AM](https://user-images.githubusercontent.com/54747669/128885159-aed3c9b6-e785-4a6e-98bd-13603b7ed9a8.png)

**Comment by NotThatDavidCross** [comment]
@mwllr The extra h3 is a rich text issue.  Not specific to the directory pages.  I'm going to look at that next.

**Comment by NotThatDavidCross** [comment]
Fixed with rich text change.

**Comment by mwllr** [comment]
![Screen Shot 2021-08-11 at 2 04 37 PM](https://user-images.githubusercontent.com/54747669/129088044-cb1c8d4f-d982-4b68-9e9f-544a6c65ba97.png)
