### ISSUE TITLE
Staff page

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#320]
https://staging.ansc.illinois.edu/directory/staff

- [x] left align whole table on the page instead of centering.
- [x] make table wider to fit space
- [x] in my.aces - change Lucas Trindade Neira, Research Specialist in Agriculture â€“ Dixon Springs Agricultural Center
lucastn@illinois.edu - has the weird character.

**Comment by NotThatDavidCross** [comment]
Table is as wide as it can be in rich text right now.

**Comment by mwllr** [comment]
done for launch
![Screen Shot 2021-08-10 at 4 46 23 PM](https://user-images.githubusercontent.com/54747669/128939315-44e7ac8f-b628-412c-bf59-d50d96ffea5e.png)
.
