### ISSUE TITLE
CSS template changes for internships

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#340]

**Comment by wrg20** [comment]
thumbnail dimensions off...itok version being used

**Comment by lizshalley** [comment]
Career Possibilities:
text fields wrap down below profile image
![Screen Shot 2021-08-10 at 4 38 36 PM](https://user-images.githubusercontent.com/8646013/128938590-f3982218-c32d-421a-a810-1d23011870d6.png)

**Comment by lizshalley** [comment]
Internships:
Remove "required" from "Description" field.
![Screen Shot 2021-08-10 at 4 40 06 PM](https://user-images.githubusercontent.com/8646013/128938741-ed8d1abd-1375-4311-8996-59427996ec9d.png)

**Comment by lizshalley** [comment]
Internships:
adjust spacing between "term" and "category" fields to match others.
![Screen Shot 2021-08-10 at 4 40 06 PM](https://user-images.githubusercontent.com/8646013/128938933-ea78a226-4bc2-4806-82fa-bdf27f5cb163.png)
