### ISSUE TITLE
Redirect news

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#366]
We do not have news at all on ANSC. It was departmental news that is outdated.
Need to redirect all 
ansc/news/**articles 
to go to: 
https://aces.illinois.edu/tags/ansc

Bill - add an issue for doing the redirect...I'll have to do it off hours as it can mess with the website if I put it in the .htaccess wrong

**Comment by nbaxley-uiuc** [comment]
@mwllr Can we close this given our earlier discussion and these issues #425 & #415

**Comment by mwllr** [comment]
moved to ACES theme repository.
