### ISSUE TITLE
All content should be in the fixed width by default

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#377]
Please keep all content in the main margins:
![Screen Shot 2021-08-16 at 1 06 08 PM](https://user-images.githubusercontent.com/54747669/129622070-19067a8b-1025-4003-9d07-190af03bdc3b.png)

**Comment by wrg20** [comment]
Merged #471

**Comment by mwllr** [comment]
not showing on sandbox today when I checked.
