### ISSUE TITLE
Setup site administrator role in Active Directory

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#380]
Assign Virgil, Liz, Ryan Dilger, Jerrica hood this role

**Comment by mwllr** [comment]
same rules as content managers, but can edit menu, all paragraph types, can use full html, redirects,

**Comment by mwllr** [comment]
setup the role on ANSC. Need to get permissions in active directory for Liz, Virgil, and Dilger. Liz and Virgil will be site admins for all of our sites. Dilger is only ANSC.
