### ISSUE TITLE
Focus state of buttons

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#383]
https://ansc.illinois.edu/about/contact-us

Clicking on a button and dragging off the button results in the text on the button disappearing.  This is an abnormal action but the focus state needs to be changed.

- [x] Fix in ANSC page above
- [x] Review other paragraphs types to make sure we're using the correct classes in all types (Should already be fixed in Rich text and General page

**Comment by nbaxley-uiuc** [comment]
If I understand this, we need to add a .il-button:focus css rule?  It looks like there is on in [the toolkit](https://cdn.brand.illinois.edu/toolkit/2.0/examples/stylesheets/buttons/index.html).  Why wouldn't we be getting that?

**Comment by wrg20** [comment]
@nbaxley-uiuc  we aren't using the il-buttons everywhere yet.  our buttons were built into the paragraphs before they produced the il-buttons.  So we have to go back and retrofit and redo the override classes for all buttons in all paragraph types.

**Comment by NotThatDavidCross** [comment]
Will be fixed for ANSC when the current dev site is moved over with the new framework.

**Comment by NotThatDavidCross** [comment]
I couldn't find a paragraph type where the button didn't show the text in that situation.
