### ISSUE TITLE
Create module to limit options in Block Reference

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#384]
https://www.mediacurrent.com/blog/drupal-8-how-reference-views-block-display-field/

Add a module to limit the blocks available in the Block Reference paragraph types to ones set in the hidden region.

**Comment by robgasc** [comment]
Added this filter plugin to the il-fw-core. Had to update the file offered on the site for D9, but otherwise seems functional. I did not include any config to change over fields that are referencing blocks. Should that become default config for the block reference paragraph? @wrg20 @nbaxley-uiuc
