### ISSUE TITLE
Remove <base> tag in html.html.twig

### ISSUE THREAD

**Issue by trubach** [ATLAS-Illinois/Illinois-Framework-Theme#392]
@wrg20 - It looks like you might use the `<base>` tag in the header to use relative paths in the theme. However, this causes issues for all relative paths. If someone adds a relative path link like `<a href="./">Link</a>`, then that link will be broken. 

Can we remove that tag from the template? Here's the line in question:

https://github.com/web-illinois/illinois_framework_theme/blob/1.x/templates/layout/html.html.twig#L39

**Comment by nbaxley-uiuc** [comment]
@wrg20 @trubach Is this resolved?

**Comment by trubach** [comment]
@nbaxley-uiuc , no, no yet.
