### ISSUE TITLE
Permissions - Content Managers

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#403]
We need to set the default Content Manager permissions to allow for:

- Adding/editing/deleting any Content Types
- Adding/editing/deleting any Paragraph Types
- Editing the Navigation menu

We will create documentation for best practices to override permissions.

**Comment by wrg20** [comment]
I believe this one is going to get moved to the ACES theme as we don't want to change the base permissions for the content manager and allow the administrator to set them to whatever they want
