### ISSUE TITLE
Add blue button style to ckeditor

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#404]
Add the following styles to ckeditor configuration
a.il-button|Base Button
a.il-button.il-white-blue|White with blue button
a.il-button.il-white-orange|White with orange button
a.il-button.il-blue|Solid blue button
a.il-button.il-orange|Solid orange button

**Comment by nbaxley-uiuc** [comment]
@wrg20 What are we using to apply classes in the ckeditor or is this just about allowed classes in Basic HTML?

**Comment by wrg20** [comment]
https://ckeditor.com/docs/ckeditor4/latest/guide/dev_howtos_styles.html

**Comment by nbaxley-uiuc** [comment]
Are these configurations in code now?

**Comment by nbaxley-uiuc** [comment]
Still need the solid blue button

**Comment by mwllr** [comment]
@wrg20  - we still have issues with the blue button, correct?

**Comment by trubach** [comment]
All other button styles are added - the blue button style isn't working for some reason that needs to be investigated further

**Comment by nhjohnstone** [comment]
investigating this, it seems to be working as it should:

https://illinois-drupal.web.illinois.edu/test-buttons

I think this was resolved already

**Comment by trubach** [comment]
Thanks for testing that, @nhjohnstone - closing
