### ISSUE TITLE
Feature Box Paragraph: Adjust image requirements

### ISSUE THREAD

**Issue by nbaxley-uiuc** [ATLAS-Illinois/Illinois-Framework-Theme#407]
- [x] Decrease the minimum image size needed to 1000x500 to match the sizes given by the campus database.
- [x] Increase the maximum file size to 10MB
- [x] Confirm that server side processing reduces the image size to something reasonable

**Comment by magjarvis** [comment]
Settings for jpeg output sizes look they are universally set to 75% quality.

**Comment by nbaxley-uiuc** [comment]
Is that typical?  What do we have them set at in LAS?

**Comment by magjarvis** [comment]
So, on the LAS sites, we are using Imagick to compress the images to 85% (go to Config>Media>Image toolkit to see the settings) ILFW is currently using GD2 settings at 75%. I wasn't sure if we wanted to change the image processor on the framework or not and didn't feel qualified enough to make that call. I would suggest making a new issue for that one.

**Comment by nbaxley-uiuc** [comment]
Good call!  Let's get these configurations into GIT and tested so we can close this one.  I created a new one #538

**Comment by trubach** [comment]
@nbaxley-uiuc , I have the image changes up on the sandbox site. When you get a chance, please test it out and go ahead and close this issue if it looks good.

**Comment by nbaxley-uiuc** [comment]
Confirmed that the checks and text have all been updated and are working.
