### ISSUE TITLE
Rich Text (and body)

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#408]
- [x] standard top margin - 45px total
- [x] standard bottom margin - 60px total
- [x] change layout to go to full 12 columns instead of 10.
- [x] margins/padding should match header (block I on left and right side of hamburger) - 20 on mobile and 30 on tablet - not currently working next to side nav.
- [x] Add option for gray background 100% of screen width. #f4f4f4 is gray background color. If they would do gray next to side nav, it wouldn't be full width, any other time, it would be full width.
- [x] title and subtitle should always be left-aligned
- [x] title and subtitle should left align visually with body text - currently they are slight moved to right. see screenshot.
- [x] make sure the "section" title is an h2, 35 px and matched the web components styling.

**Comment by mwllr** [comment]
![Screen Shot 2021-09-15 at 9 25 16 AM](https://user-images.githubusercontent.com/54747669/133465620-c834216e-1f00-4f7e-aff2-1e4da087b57c.png)

**Comment by wrg20** [comment]
> 
> 
> ![Screen Shot 2021-09-15 at 9 25 16 AM](https://user-images.githubusercontent.com/54747669/133465620-c834216e-1f00-4f7e-aff2-1e4da087b57c.png)

I'm not sure where this is showing up @mwllr

**Comment by wrg20** [comment]
We can't really remove the subtitle without removing possible content from websites....I can exclude the subtitle from showing in the template but that would potentially be confusing for users if they put something into the UI.

**Comment by mwllr** [comment]
then leave it for now. creates issues for h2, h3, etc....

**Comment by mwllr** [comment]
I removed the 

- [ ] remove section title - we really don't need it and it messes with adding h2 or h3...

**Comment by wrg20** [comment]
Going to split out the configuration changes into another issue from code changes.

**Comment by wrg20** [comment]
Created issue #480 for the configuration changes so I can submit the code changes on this issue.

**Comment by wrg20** [comment]
Merged #481 for margins/padding and large 12 columns
