### ISSUE TITLE
Add named anchor link option. 

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#413]
- [x] Add the https://www.drupal.org/project/anchor_link module

Add anchor links to paragraphs to be able to link to???

ability to put in advising for example, then go to page xyz#advising.

Specifically Rich Text, but will need overall.

**Comment by nbaxley-uiuc** [comment]
Related to #459

**Comment by nbaxley-uiuc** [comment]
LAS uses this module - https://www.drupal.org/project/anchor_link

**Comment by trubach** [comment]
Anchors are now available in the rich text editor:

![image](https://user-images.githubusercontent.com/56594946/144085105-8761a86e-1059-47fe-9faa-452193782dae.png)

I'm closing the issue for now. If we want to automatically add anchors to every paragraph, I think that might need to be a separate issue.

**Comment by trubach** [comment]
An example of the anchor in action is at: https://illinois-drupal.web.illinois.edu/paragraphs/rich-text-2#anchor_test
