### ISSUE TITLE
News - Highlighted news block config

### ISSUE THREAD

**Issue by magjarvis** [ATLAS-Illinois/Illinois-Framework-Theme#414]
- [x] The view needs to have a filter to only show "Promoted to front page" content.
- [x] Title of the block should remain inside the page width

**Comment by nbaxley-uiuc** [comment]
@magjarvis I added a To Do to make the title a link.  The button and the image are already links, but it feels like the title should be as well unless there was a design decision made elsewhere.

**Comment by nbaxley-uiuc** [comment]
P.S. I added this block the front page of the sandbox site and put in some sample stories.

**Comment by nbaxley-uiuc** [comment]
I also added a To Do that says the view should only show content that is "Promoted to front page".  Working to clarify why all content currently defaults to promoted to front page.
