### ISSUE TITLE
News- More news block layout/design

### ISSUE THREAD

**Issue by magjarvis** [ATLAS-Illinois/Illinois-Framework-Theme#417]
- [x] update background color to darker gray (#f4f4f4 ?)

**Comment by mwllr** [comment]
small tweaks. @magjarvis 
![Screen Shot 2021-10-28 at 4 30 44 PM](https://user-images.githubusercontent.com/54747669/139339732-91736a42-db3e-436f-a5dc-b369a26fd5b6.png)
