### ISSUE TITLE
Update .paragraph class with proper top and bottom padding

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#418]
- [ ]  60 px padding inside top of paragraph total
- [ ]  75 px padding inside bottom of paragraph total
- [ ] Set bottom padding to 0px on icon row PT because the icons already have the bottom padding
- [ ] Review any other PTs that may contain children with a similar situation to icon row

**Comment by nbaxley-uiuc** [comment]
Maggie will test the paragraph spacing with the to line with what the design specs are wanting.

**Comment by magjarvis** [comment]
closing issue and replacing with #564, #565, & #566
