### ISSUE TITLE
Allow 5 icons on a row in Icon Row PT

### ISSUE THREAD

**Issue by nbaxley-uiuc** [ATLAS-Illinois/Illinois-Framework-Theme#420]
It looks like changing the flex-basis from 25% to 20% on the rule below will fix it, but I'll leave the specifics to the experts
`.paragraph--type--icon-row .field--name-field-icon-row-content .field__item`

We still need to support 4 and fewer icons evenly spaced in a row after this change.

**Comment by mwllr** [comment]
Great!
![Screen Shot 2021-09-30 at 10 47 14 AM](https://user-images.githubusercontent.com/54747669/135488393-3bbf8c2a-2ac4-4b25-8f97-c3e3e93dc78c.png)
![Screen Shot 2021-09-30 at 10 47 17 AM](https://user-images.githubusercontent.com/54747669/135488417-f5e8c84d-10d0-4a0f-ae26-33714f2c1072.png)
