### ISSUE TITLE
Twitter icon link in footer isn't showing up

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#422]
We spun up cpsc.illinois.edu and I added a twitter link. It's not showing in footer.
It is entered in the Drupal interface setting.
- Nevermind - I just didn't have the s in the URL..... now just something we need to document.....

**Comment by nbaxley-uiuc** [comment]
Documentation [here](https://drupal.webtheme.illinois.edu/site-setup/adding-social-media-accounts)
