### ISSUE TITLE
link colors on colored backgrounds for split feature, video feature, feature box, call to action, and hero section

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#426]
![Screen Shot 2021-09-30 at 10 40 55 AM](https://user-images.githubusercontent.com/54747669/135487661-558e060c-863e-4bd3-8ee8-2771852091e1.png)

- [x] make sure you go back and remove the 2 background colors of altgeld and industrial-blue from Merge #461 
- [x] link colors for colored backgrounds should be as follows:

![Screen Shot 2021-09-29 at 3 21 17 PM](https://user-images.githubusercontent.com/54747669/135342682-a86f5397-9ba1-4246-91c2-12cee60eaf9b.png)

**Comment by wrg20** [comment]
merge #427 changed the background colors, put black in for the hover on orange gradient

**Comment by wrg20** [comment]
black color on altgeld fails with normal text.
![image](https://user-images.githubusercontent.com/1544079/134980642-adbbe103-a000-451e-92c7-938b62928221.png)

**Comment by mwllr** [comment]
It only needs to pass AA. ;)

**Comment by wrg20** [comment]
Merge #461 updated link colors, headings and added two additional background colors (altgeld, industrial-blue that may be introduced to paragraphs, buttons will need to be worked out for these two)

**Comment by mwllr** [comment]
not adding altgeld or industrial-blue as background colors. They are part of the gradients.

**Comment by mwllr** [comment]
will review after design on thursday.

**Comment by wrg20** [comment]
Merged #482 removes the two other background colors.
