### ISSUE TITLE
clickable cards - page alignment

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#428]
- [ ] left/right margins are off for clickable cards they are outside of the 1140 page alignment with the block I and search box.

**Comment by mwllr** [comment]
so close.... at least it's inside the 1140 px now.... but it's inside by about 40px
![Screen Shot 2021-09-30 at 12 15 27 PM](https://user-images.githubusercontent.com/54747669/135501045-a6a97970-6f5f-4893-9894-2eaae26b266f.png)
.

**Comment by wrg20** [comment]
Merge #464

**Comment by mwllr** [comment]
still have alignment issues.
all need to align with left margin on desktop.
![Screen Shot 2021-10-13 at 11 37 34 AM](https://user-images.githubusercontent.com/54747669/137176689-1881541c-b5dc-488d-ac84-10b816fc5723.png)

**Comment by mwllr** [comment]
margins are off on mobile too. Side nav is different than the ones without side nav. Then the full-width ones are different too.....
they are going off the screen instead of staing within the margins of the block I and search box for all big buttons on mobile.

Screenshots are from page: https://illinois-drupal.web.illinois.edu/paragraphs/big-buttons

![36ae89d5-3c64-4deb-836a-4c17c4394eff](https://user-images.githubusercontent.com/54747669/137177283-68a38915-42ac-420c-a4ae-6c674abf466d.jpg)
![bfdb0133-43b0-4b56-9e74-40a08addfc87](https://user-images.githubusercontent.com/54747669/137177284-1af01bb6-82e8-45c4-9645-8dc5a0860838.jpg)
![c5f343c9-68e1-42c9-81bb-fadf3c1af0b2](https://user-images.githubusercontent.com/54747669/137177286-aaf336c7-dafe-4983-b229-b8cb9d6ae93e.jpg)
.

**Comment by wrg20** [comment]
Merged #487 - Fixed margins and padding

**Comment by mwllr** [comment]
good to go! aligns!

**Comment by wrg20** [comment]
Need to fix background colors. Changed them, going to revert back

**Comment by wrg20** [comment]
Fixed with merge #498
