### ISSUE TITLE
default home page alignment

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#435]
Get featured news to stay within 1140px page margins. Should left align with orange text that starts with Bollero...
![Screen Shot 2021-09-29 at 3 11 21 PM](https://user-images.githubusercontent.com/54747669/135341501-47a16212-0fb2-464f-8b46-2fbf813f3262.png)

**Comment by nbaxley-uiuc** [comment]
Duplicated in #414
