### ISSUE TITLE
Spotlight family - Change to sidebar layout 

### ISSUE THREAD

**Issue by nbaxley-uiuc** [ATLAS-Illinois/Illinois-Framework-Theme#439]
- [x]  Change listing page to sidebar layout
- [x]  Change detail page layout to sidebar

Need to create a new Page.twig file for the Spotlight CT layouts and remove the if condition around hte layout type. Need to "keep both the first second sidebar"

**Comment by robgasc** [comment]
@nbaxley-uiuc Should this include the paragraphs in sidebar feature as well? Or would it be ok to just include the sidebar if it has content in it, i.e. if someone adds a spotlight to a menu, the menu will show in the sidebar, or a block to the sidebar, etc?

**Comment by robgasc** [comment]
Additionally, should the sidebar field, when you set it to show sidebar, always show a sidebar, even if there is nothing in it?

**Comment by nbaxley-uiuc** [comment]
I think it's actually simpler than that.  The listing and detail pages should always use the layout that includes the sidebar region.  If understand it correctly, the actual content to show in that region is controlled by the sidebar menu element itself.  I'd prefer NOT to have a sidebar on/off selector on the spotlight pages.

**Comment by robgasc** [comment]
This is done, the sidebar will only display if the sidebar has a block display on the spotlight, including if the spotlight is in a menu that displays.
