### ISSUE TITLE
Need to resolve multiple drag arrow icons in edit form.

### ISSUE THREAD

**Issue by nbaxley-uiuc** [ATLAS-Illinois/Illinois-Framework-Theme#440]
According to Tyler, this is resolved in the latest Drupal 9 release. See the bottom of the issue at: https://www.drupal.org/project/drupal/issues/3092181.  Need to confirm after #393 is complete.

**Comment by trubach** [comment]
Tested and confirmed fixed in Drupal 9

![image](https://user-images.githubusercontent.com/56594946/139104390-9946d045-31ee-428b-94ac-5c895ba91670.png)
