### ISSUE TITLE
Contact paragraph sidebar alignment

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#444]
- [x] Adjust the contact paragraph to 2 columns on desktop when side navigation is present.
- [x] for image left - make sure content is aligned left
- [x] on side nav left align both buttons have funny spacing - should left align with text....see screenshot down the page a bit.
- [x] email address isn't linking

![Screen Shot 2021-09-30 at 10 44 54 AM](https://user-images.githubusercontent.com/54747669/135488159-a21ee98b-e662-45fd-add1-35a199a118ed.png)
:

**Comment by wrg20** [comment]
Merge #463 adjusts the ordering of the body text for the proper alignment.

**Comment by mwllr** [comment]
BOTH buttons should left align with text.

![Screen Shot 2021-10-13 at 11 29 48 AM](https://user-images.githubusercontent.com/54747669/137175151-9838d73a-af46-447f-8b4b-b948f0266ef2.png)
.

**Comment by wrg20** [comment]
The button situation is tough because you can not predict the length of the button and add the appropriate margin around it.  Therefore, each button stands alone on a line.

**Comment by mwllr** [comment]
Looks much better!!! done.
