### ISSUE TITLE
Hero paragraph

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#452]
- [ ] the alignment isn't working when you don't have an image-should still be able to have left/right and top/bottom without images.

**Comment by wrg20** [comment]
Merged #472

**Comment by mwllr** [comment]
working now.

**Comment by mwllr** [comment]
![Screen Shot 2021-10-20 at 9 15 45 AM](https://user-images.githubusercontent.com/54747669/138110564-58db46e4-6ac3-4efb-890c-a30ca29f7327.png)
