### ISSUE TITLE
Call to action - when icon is used

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#453]
- [x] desktop - left align when icon is used
- [ ] mobile - center when icon is used
- [ ] tablet - left align when icon is used 

See designs on #405

**Comment by nbaxley-uiuc** [comment]
@mwllr On tablet, should the icon be left aligned on the same line with the other content, or on the line as it is now?  Example: https://illinois-drupal.web.illinois.edu/paragraphs/call-action

**Comment by mwllr** [comment]
@nbaxley-uiuc 
--on tablet, icon needs to move to the left a little.
--still need centered on mobile.

![Screen Shot 2022-02-18 at 3 28 32 PM](https://user-images.githubusercontent.com/54747669/154763973-c02777ac-7135-4488-aad8-98da2198b68c.png)
