### ISSUE TITLE
Add DNS Prefetch for web components

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#460]
Add DNS Prefetch for the web toolkit components CDN. <link rel="dns-prefetch" href="//cdn.brand.illinois.edu">

**Comment by wrg20** [comment]
https://www.drupal.org/project/cdn - may need to implement a more aggressive solution.

**Comment by trubach** [comment]
What issue is this trying to solve? Could you add some detail on what the problem is?

**Comment by trubach** [comment]
Add DNS prefetch in PR #592

See https://github.com/web-illinois/illinois_framework_theme/pull/592/files#diff-fb53c185027944f6a7c43c0056adb002dbe8dc497a54887fa8b324d7beeaafbc
