### ISSUE TITLE
Change Basic HTML configurations to include more buttons by default

### ISSUE THREAD

**Issue by nbaxley-uiuc** [ATLAS-Illinois/Illinois-Framework-Theme#466]
- [x] Table editor
- [x] Paste text
- [x] Paste from Word
- [x] Sub script
- [x] Super script
- [x] Embed Media button https://www.drupal.org/docs/core-modules-and-themes/core-modules/media-library-module/embedding-media-with-ckeditor

For now we are leaving out these configurations
- Text align (left/right/center/justify) - these will be handled by theme styles
- Undo/Redo - These can be done natively in the browser

**Comment by nbaxley-uiuc** [comment]
@NotThatDavidCross are you working on this issue?

**Comment by trubach** [comment]
Changes brought into the profile through PR web-illinois/illinois_framework_profile#16
