### ISSUE TITLE
lists - alignments

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#468]
- [x] Force all lists to be left aligned

left and centered lists need to display correctly.

Here's an example in call to action, but this will happen globally where alignment can be changed.
![Screen Shot 2021-10-13 at 11 48 09 AM](https://user-images.githubusercontent.com/54747669/137177852-e10a4bc6-dd38-460e-9ee8-855a3f1ecd63.png)
![Screen Shot 2021-10-13 at 11 48 11 AM](https://user-images.githubusercontent.com/54747669/137177854-31b08a7d-bb38-4261-ae67-bde472fed268.png)

**Comment by nbaxley-uiuc** [comment]
@mwllr Just to clarify:
**When they are right aligned** the bullets should be to the right of the text with all bullets flush to the right side?
**When they are center aligned** the bullets should be tight to the text, on the left side of the text, and will vary left to right depending on the text length.

- I think for right align we want to add a `direction: rtl;` rule ([explanation here](https://css-tricks.com/forums/topic/aligning-list-items-and-bullets-to-the-right/#post-244598)) - [codepen here](https://codepen.io/Paulie-D/pen/QEoboA)
- For center we need to add `list-style-position: inside;` rule ([example here](https://stackoverflow.com/questions/10431037/css-right-aligned-list))

**Comment by nbaxley-uiuc** [comment]
Design group has decided that all lists should be left aligned.

**Comment by wrg20** [comment]
merge #654 adjusts all lists to left alignment
