### ISSUE TITLE
text link focus states - set no outline as default

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#469]
Need to set a default so the browser doesn't allow for a box to be applied to text links for the focus states.

![Screen Shot 2021-10-13 at 11 47 55 AM](https://user-images.githubusercontent.com/54747669/137177969-08be28b3-d494-475d-a12e-0989d99d1816.png)

**Comment by nbaxley-uiuc** [comment]
Fixed with #535
