### ISSUE TITLE
Style for Webtools Calendar

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#470]
Design a style in insert a script for webtools calendar.

**Comment by nbaxley-uiuc** [comment]
@magjarvis is working on turning calendar embeds into a paragraph type to encapsulate the JS and addressing the formatting will be part of this.

**Comment by mwllr** [comment]
Is working!! Maggie still tweaking a few more things after we talked today.

**Comment by mwllr** [comment]
Calling is great for 2.1 release. Will continue to tweak and add to it for 2.2.
![Screen Shot 2022-03-04 at 9 47 47 AM](https://user-images.githubusercontent.com/54747669/156795066-10b64904-0f57-40fa-ba85-58eda50511e9.png)
