### ISSUE TITLE
Interface typo(s)

### ISSUE THREAD

**Issue by dlstrong** [ATLAS-Illinois/Illinois-Framework-Theme#473]
In the screen shot taken at https://drupal.webtheme.illinois.edu/sites/default/files/inline-images/drupal_subfooter.png in the documentation, there are several instances of "Text to displayed."

That should either be "Text to display" or "Text to be displayed." I'm more inclined toward the more-active "Text to display" myself.

**Comment by wrg20** [comment]
Merge #521 changed all instances to "Text to display"
