### ISSUE TITLE
Docs: Simplify the email domain explanation

### ISSUE THREAD

**Issue by dlstrong** [ATLAS-Illinois/Illinois-Framework-Theme#474]
on https://drupal.webtheme.illinois.edu/site-setup/basic-site-settings I'm reading "Use an address ending in your site's domain to help prevent this email from being flagged as spam." 

I'm inclined to suggest "Use an address ending in @illinois.edu to help prevent this email from being flagged as spam" for two reasons:

a) People who don't know what a domain is aren't going to know how to do that

b) People who DO know what a domain is, and who are installing Drupal on cPanel, are more likely going to go "oh God do I need to run my own mail server on mysite.web.illinois.edu in order to make the domain match enough?" when we really don't want them doing that

Is that simplification still accurate? Is @illinois.edu what we want them to be using? 

Or if they're (for example) mysite.web.illinois.edu, are they actually going to need myemail@mysite.web.illinois.edu as their advertised address in order to keep the spam trappper happy? (I'm seriously hoping @illinois.edu is good enough.)

Once someone answers that question either on Teams or here, and once I have editor rights, I could make the edit - I want to make sure it's accurate though.

**Comment by nbaxley-uiuc** [comment]
It's been updated to "@illinois.edu"
