### ISSUE TITLE
Remove faculty explorer images

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#478]

**Comment by nbaxley-uiuc** [comment]
@wrg20   Is this still open?  Do you have an example of the issue?  Is it specific to ACES or more systemic?

**Comment by NotThatDavidCross** [comment]
It looks like Bill took care of this in this commit:  https://github.com/web-illinois/illinois_framework_theme/commit/7739b0da854aecd03b5f3d2687c04ef2f097652f

Those are definitely the Faculty Explorer images.
