### ISSUE TITLE
Video Feature Paragraph

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#48]
![image](https://user-images.githubusercontent.com/1544079/113034795-25aa4f00-9158-11eb-8959-54e52850b51e.png)

**Comment by mwllr** [comment]
Add field for spacing before paragraph: no, small, med, lg, xlg..
See Call to Action Narrow for example already added.

**Comment by lizshalley** [comment]
- [ ] white copy on orange, blue, and gradient backgrounds
- [ ] video does not stack with text box on mobile
![TEST - Feature Video  Animal Sciences  University of Illinois](https://user-images.githubusercontent.com/8646013/124162166-d54ad200-da63-11eb-843b-f2ab3784650d.jpeg)

**Comment by lizshalley** [comment]
need white text on blue, orange, and gradient backgrounds.
![Screen Shot 2021-08-10 at 11 25 30 AM](https://user-images.githubusercontent.com/8646013/128896556-ff7dff40-7e9f-4f7a-b502-ed6a58868fcf.png)
