### ISSUE TITLE
Content on fund pages ins't contained

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#483]
Once you update a fund listing, the content is pushed out to the left side of screen. can we align in main content section?

![Screen Shot 2021-10-21 at 5 38 04 PM](https://user-images.githubusercontent.com/54747669/138367655-a53f4cf0-40a8-40d3-8853-72c28e2837f1.png)

**Comment by nbaxley-uiuc** [comment]
The fund pages aren't designed to be viewed publicly.  The funds will always be shown in a fund listing page.  It would be nice to fix this just for completeness, but I think it's a low priority

**Comment by magjarvis** [comment]
Closing this issue as it looks like this is fixed in 3.x or maybe with the bootstrap update. This is how it looks on the sandbox:

![Image](https://user-images.githubusercontent.com/8452264/214930676-f61796e3-b3a8-44dc-a8e5-0dfa3042cff2.png)
