### ISSUE TITLE
Fund page updating

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#484]
once you make a fund page with funds. Save it, then need to make an edit to a fund like updating the fund number. You have to go back and put the fund back into the page. just updating the fund doesn't update the page.
Ask Melissa if questions.

**Comment by nbaxley-uiuc** [comment]
This is a caching issue.  If you open the page as a logged out person or clear the cache manually the number gets updated.  I don't think we need to do any changes here.
