### ISSUE TITLE
Call to Action Narrow paragraph

### ISSUE THREAD

**Issue by magjarvis** [ATLAS-Illinois/Illinois-Framework-Theme#50]
Call to action paragraph, narrow version

**Comment by mwllr** [comment]
- [x] page margins need set - (1600px margins for 1200+)- NOT DOING NOW.....
- [x] mobile - go to totally centerd for all options?
- [x] mobile - background go all the way to screen edge, no white border.
- [x] tablet - alignment options - once stacked, go to centered?

**Comment by mwllr** [comment]
![Screen Shot 2021-06-23 at 12 15 15 PM](https://user-images.githubusercontent.com/54747669/123140280-b83b5100-d41c-11eb-98c8-9eef3a3e236e.png)

![Screen Shot 2021-06-23 at 12 15 46 PM](https://user-images.githubusercontent.com/54747669/123140328-c6896d00-d41c-11eb-9651-8574de8269f8.png)
