### ISSUE TITLE
Grouped Feature width issue

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#504]
Large column set to 9 instead of 12

**Comment by nbaxley-uiuc** [comment]
@wrg20  Is this still an issue?

**Comment by wrg20** [comment]
Not sure if this is an issue anymore @mwllr any thoughts?  Grouped Feature basically doesn't work without a sidenav.  Maybe that's what I was talking about.

**Comment by mwllr** [comment]
still an issue. should work if we have side nav or not.

**Comment by mwllr** [comment]
width issue has been fixed along the way.
