### ISSUE TITLE
Call to action narrow padding

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#506]
The padding for the call to action is adjusted by the

**Comment by wrg20** [comment]
Fixed width is being overridden.  
![image](https://user-images.githubusercontent.com/1544079/139344217-ffec1201-998b-465f-ac1a-09db33df52e2.png)

**Comment by mwllr** [comment]
closing this. there are more issues than what's above. Will start fresh.
