### ISSUE TITLE
Editor - change to Gin theme

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#509]
When editing pages, it's a very narrow view. Make it a wider view please
![Screen Shot 2021-10-28 at 10 51 20 PM](https://user-images.githubusercontent.com/54747669/139375477-a4ee0ed5-efcf-491a-b5ea-da9e3bede0b1.png)
.

**Comment by mwllr** [comment]
@nbaxley-uiuc - I believe this is done.

**Comment by wrg20** [comment]
https://www.drupal.org/project/drupal/issues/3169297

patch we can apply to make this happen

**Comment by wrg20** [comment]
need to apply the above patch then place a file in the /sites/default/files/claro folder called custom.css and add

``@media screen and (min-width: 61rem) {
  .layout-region--node-main .layout-region__content,
  .layout-region--node-footer .layout-region__content {
    max-width: 100% !important;
    margin-right: auto;
    margin-left: auto;
  }
}
``

Works like a charm 
![image](https://user-images.githubusercontent.com/1544079/156854259-793f5752-f9e5-4dfe-9e89-404981a36aa3.png)

**Comment by trubach** [comment]
I came across a [Drupal article](https://devcollaborative.com/blog/enhance-your-drupal-websites-authoring-experience-part-1-modernize-admin-theme-gin) that recommends using the ["Gin" admin theme](https://www.drupal.org/project/gin).

It looks like the Gin admin theme makes the editor WYSIWYG wider, plus it includes some really nice UX improvements. @mwllr , would you mind looking over that article? How would you feel about switching our admin theme to Gin?

**Comment by nbaxley-uiuc** [comment]
That Gin theme looks really nice.  Feels much more modern than the one we're on now.  Feels like something that would need some testing but what do others think about putting this in 2.2?  @mwllr ? @wrg20 ?

**Comment by trubach** [comment]
Fixed in PR web-illinois/illinois_framework_profile#28 by using the Gin admin theme
