### ISSUE TITLE
Media Module - PDF alias links not working

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#52]
When a PDF is uploaded into the media library, you have an option to create an alias for that, but that functionality.

**Comment by nbaxley-uiuc** [comment]
In my testing, the PDFs uploaded to the media library are accessible with the full URL, but the alias takes you to the edit form.  There is an example on the sandbox [here](https://drupal-sandbox.webtheme.illinois.edu/DummyPDF.pdf?destination=/admin/content/media-grid).  [This URL gives you the document](https://drupal-sandbox.webtheme.illinois.edu/sites/default/files/2021-11/Test%20Document.pdf), but [this one takes you to the form which requires site login](https://drupal-sandbox.webtheme.illinois.edu/DummyPDF.pdf) (Both need the shib login for ANY site access)

**Comment by robgasc** [comment]
So there is a setting that needs to change, called Standalone URL in the media settings. I've enabled this on the site, and updated the alias that was pointing to the edit page. It takes you to the media item itself, not directly to the document.

**Comment by mwllr** [comment]
@robgasc - is it always supposed to take you to the media page, and not the document?
As a user, I would expect it to take you to the document.
@nbaxley-uiuc 

https://illinois-drupal.web.illinois.edu/52-media-module

**Comment by robgasc** [comment]
> 

The choice is either a nice alias, or the full document url in our current setup. @mwllr

**Comment by nbaxley-uiuc** [comment]
To make the formatting a little better, let's make the following changes:

- Place the link/image thumbnail/video inside the page width
- Add padding below the link/image thumbnail/video to separate it from the footer
- Increase the font size on links
- Increase the video size on video previews

**Comment by robgasc** [comment]
The styling is now present for the page.
