### ISSUE TITLE
News - archive block 

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#524]
- [x] needs styling to heading to align within page

**Comment by nbaxley-uiuc** [comment]
I think that the heading is in the correct location, but there is extra space to the left of the content.  When the news listing page is full screen (no sidebar) there seems to be more, but there is still some when there is a sidebar as well.  [Full screen Example here](https://mcb.web.illinois.edu/news) [Sidebar example here](https://drupal-sandbox.webtheme.illinois.edu/news)

**Comment by nbaxley-uiuc** [comment]
Here is an [example of the block heading not being contained](https://drupal-sandbox.webtheme.illinois.edu/news-block-test-page).  This is also a problem on the Highlighted News block on the home page of the sandbox.  If we can define a solution that catches ANY block title that would be best.

**Comment by nbaxley-uiuc** [comment]
The change needs to be to move the top margin from the tagline to the H2 subtitle so the space is only applied when the subtitle is there.

**Comment by robgasc** [comment]
Just pushed fix that addresses the original issue. Not sure what the last comment from @nbaxley-uiuc is related to, but it seems unrelated to this issue.
