### ISSUE TITLE
News - individual article

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#525]
- [x] remove 30 px margin above byline (essentially removes 30px between title and horizontal rule above author) when subtitle isn't used, too much space shows.

**Comment by nbaxley-uiuc** [comment]
@mwllr I think it's the bottom margin on the H1.  Is that a change that needs to be made just on news or should it be made on ALL pages?

**Comment by nbaxley-uiuc** [comment]
Example pages for testing:

- [News with no subtitle](https://drupal-sandbox.webtheme.illinois.edu/news/2018-09-28t183651/bollero-lead-college-aces-interim-dean)
- [News with subtitle](https://drupal-sandbox.webtheme.illinois.edu/news/2019-09-27t183230/psychology-faculty-investigates)
- [Content page with title](https://drupal-sandbox.webtheme.illinois.edu/contact-test/undergraduate-degrees-big-buttons)

**Comment by nbaxley-uiuc** [comment]
The change needs to be to move the top margin from the tagline to the H2 subtitle so the space is only applied when the subtitle is there.
