### ISSUE TITLE
Table Styles in Rich Text/Wysiwyg

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#529]
Tables are defined in the toolkit. Need to be added to Drupal rich text.
https://cdn.brand.illinois.edu/toolkit/dev/examples/stylesheets/tables/index.html

**Comment by nbaxley-uiuc** [comment]
This MIGHT get fixed putting il-formatted onto the main tag.  Needs testing

**Comment by magjarvis** [comment]
il-formatted is currently styling the tables
