### ISSUE TITLE
Fix formatting on News CT Teaser display

### ISSUE THREAD

**Issue by nbaxley-uiuc** [ATLAS-Illinois/Illinois-Framework-Theme#532]
- [x] The node title is displaying outside the page width
- [x] The byline is not showing author and date correctly.  Currently shows blank area with border on top and bottom.  Should be formatted as it is on the main article page.

**Comment by nbaxley-uiuc** [comment]
[Example here](https://drupal-sandbox.webtheme.illinois.edu/taxonomy/term/4)

**Comment by robgasc** [comment]
What fields should be on the teaser? And for the byline/date, should it match the full article? I'm not sure if this was ever designed formally anywhere, so it is kind of unclear what it needs to look like.

I do have this addressed overall, the full view was being applied to the teaser view as well because the template was named for the generic level.

**Comment by trubach** [comment]
Re-opening to verify that the issues are fixed. @nbaxley-uiuc , the sandbox site should be updated, can you see that the teasers are displaying correctly?

**Comment by robgasc** [comment]
@trubach No, that pull definitely doesn't. That pull request only adds the teaser template, still need to get the styling in place.

**Comment by nbaxley-uiuc** [comment]
Agreed.  Still [needs some work.](https://drupal-sandbox.webtheme.illinois.edu/taxonomy/term/4)  .  @robgasc can we roll all of the changes and application into one push?

**Comment by trubach** [comment]
Reopening to get approval of changes

**Comment by trubach** [comment]
@nbaxley-uiuc - the sandbox has been rebuilt with the latest changes. Mind verifying that this issue is resolved and close it?

**Comment by robgasc** [comment]
Ok, so even linking a pull request to an issue will close the issue. Reopening for review!

**Comment by nbaxley-uiuc** [comment]
Looks good!
