### ISSUE TITLE
Need to allow users to upload files into the Media Library through the ckEditor

### ISSUE THREAD

**Issue by nbaxley-uiuc** [ATLAS-Illinois/Illinois-Framework-Theme#534]
Use the same libraries that we use in LAS.

- [x] Add libraries to modules
- [x] Configure Basic HTML to allow uploads
- [x] Add the LinkIt library and configure it to be the default link tool

**Comment by robgasc** [comment]
The media library is already configured to allow uploads in editor for any media type. If you edit a standard node set to Basic HTML, there is an "Insert from Media Library" button which has a gui for doing uploads. More clarification would be excellent @nbaxley-uiuc

**Comment by robgasc** [comment]
Between me (and lots of debugging the update process with @trubach ) this is now ready to test on the sandbox.

**Comment by mwllr** [comment]
@robgasc - shows up in basic content, but not in rich text...
https://illinois-drupal.web.illinois.edu/534-upload-files-media-library-through-ckeditor

**Comment by robgasc** [comment]
> @robgasc - shows up in basic content, but not in rich text... https://illinois-drupal.web.illinois.edu/534-upload-files-media-library-through-ckeditor

Hi @mwllr, I've made a separate issue for this, since it is unique to the implementation of the rich text. https://github.com/web-illinois/illinois_framework_theme/issues/605
