### ISSUE TITLE
All H2s need to be orange and have zero margin on top despite il-formatted or other overrides

### ISSUE THREAD

**Issue by nbaxley-uiuc** [ATLAS-Illinois/Illinois-Framework-Theme#537]
Currently being applied in the RT template file, but needs to be universal

**Comment by mwllr** [comment]
make sure illini orange on white and altgeld on gray.

**Comment by nbaxley-uiuc** [comment]
@mwllr Is it not possible to just use altgeld always for simplicity?

**Comment by nbaxley-uiuc** [comment]
[Example of an H2 in a non-RT situation.](https://drupal-sandbox.webtheme.illinois.edu/news/2019-09-27t183230/psychology-faculty-investigates)

**Comment by mwllr** [comment]
technically only need to remove the padding on h2 if it is the first h2 in the paragraph....Only removing the padding/margin so there is the 45 px paragraph padding to start the rich text paragraph with.
h2:first-of-type

**Comment by magjarvis** [comment]
looks like there is already a :first-child class in il-formatted. I've adjusted the colors for RT, News, and Spotlight
