### ISSUE TITLE
Evaluate image processing configurations

### ISSUE THREAD

**Issue by nbaxley-uiuc** [ATLAS-Illinois/Illinois-Framework-Theme#538]
LAS sites currently use Imagick to compress all images to 85% (go to Config>Media>Image toolkit to see the settings) .ILFW is currently using GD2 settings and compressing to 75%.   Do we want/need to make any changes to these tools and or levels?

**Comment by trubach** [comment]
I've got a fix for this in the works @wrg20

**Comment by wrg20** [comment]
Nice!

**Comment by trubach** [comment]
The default image processor is now set to imagick. I included an update hook that will set it to imagick for existing sites. See PR on the core module above.
