### ISSUE TITLE
Boxed Feature Paragraph

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#55]
![image](https://user-images.githubusercontent.com/1544079/113782127-4eea5280-96f7-11eb-81ee-15692d97fdd4.png)

**Comment by wrg20** [comment]
Ready for review @lizshalley @mwllr - Posted login credentials on slack for you to sign in on the https://wmswgutierr.web.illinois.edu to test out the feature boxed.

**Comment by lizshalley** [comment]
@wrg20 I still can't see it live...

**Comment by wrg20** [comment]
Make the tablet breakpoint behave like mobile(phone) breakpoint

**Comment by melissawaller78** [comment]
please remove gray outline around colored background behind text.
![Screen Shot 2021-05-05 at 2 03 36 PM](https://user-images.githubusercontent.com/20865753/117195274-b8b75400-adaa-11eb-860f-d37ffee0a71a.png)

**Comment by melissawaller78** [comment]
also, on the largest view, the margins are much larger within the colored box. Please make them the same as the next breakpoint down. 
Use these margins for both screen sizes.
![Screen Shot 2021-05-05 at 2 33 00 PM](https://user-images.githubusercontent.com/20865753/117198725-fd44ee80-adae-11eb-9bca-71f7516b12e2.png)
in screen grab below, the margins are too big for adding the box. Match these to above screen grab.
![Screen Shot 2021-05-05 at 2 32 55 PM](https://user-images.githubusercontent.com/20865753/117198715-fa49fe00-adae-11eb-891a-a9978bf44eda.png)

**Comment by mwllr** [comment]
still need to remove gray outline on box background please.

**Comment by mwllr** [comment]
Add field for spacing before paragraph: no, small, med, lg, xlg..
See Call to Action Narrow for example already added.
- [ ] tablet and mobile text box background should be 100% opaque if possible
- [ ] remove text box gray outline
- [ ] white text on orange, blue, and gradient backgrounds
