### ISSUE TITLE
Accordion - add component

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#561]
Need to add accordion as an option for paragraph type.  Need the ability to add text above and below the accordion in the paragraph.

Fields:
Heading - h2
Text Box - so we can put a paragraph or more before the accordion.
Accordion section 
- options: il‑accordion_multiple or il‑accordion
- options:il‑details-solid or il‑details-bordered
- each accordion item will have the summary and then area for text/content plus a checkbox for open="" if you want that item to stay open

Text Box - so we can put a paragraph or more after the accordion.

https://github.com/web-illinois/toolkit/wiki/il-accordion

**Comment by trubach** [comment]
@mwllr  - How strongly do you feel that we need the options for opening single/multiple accordions at a time, along with sold/bordered display? I'm inclined to keep the editing form simple, and set it to multiple allowed open, and using the solid display. 

Then, in theory, someone could override the templates we have in our theme to change the behavior of the accordions. They'd need to add their own TWIG files, however.

What do you think? I have a working solution on my localdev currently, minus the multiple/single and solid/bordered options.

**Comment by trubach** [comment]
I talked with Melissa and she's OK with merging what's currently developed. I will create a new ticket to add the solid/bordered and multiple open options.

**Comment by mwllr** [comment]
yep. Melissa will take basic functionality now and upgrades later ;)

**Comment by mwllr** [comment]
Accordion paragraph type added and functions properly.
https://illinois-drupal.web.illinois.edu/paragraphs/accordion
