### ISSUE TITLE
Call to action 

### ISSUE THREAD

**Issue by magjarvis** [ATLAS-Illinois/Illinois-Framework-Theme#57]
Call to action paragraph, with image option.

**Comment by lizshalley** [comment]
Need to update the subtitle to bold font and change color to white on orange and blue backgrounds and orange gradient background.

**Comment by lizshalley** [comment]
left- and right-fade fingerprints do not populate on gradient backgrounds.

**Comment by lizshalley** [comment]
all text on orange and blue backgrounds, including gradient versions, should be white.

**Comment by lizshalley** [comment]
buttons should be optional for CTA

**Comment by lizshalley** [comment]
title centered alignment option doesn't match body centered alignment.
![Screen Shot 2021-06-09 at 10 47 57 AM](https://user-images.githubusercontent.com/8646013/121387540-5e149900-c910-11eb-8f78-80264c5f9576.png)

**Comment by mwllr** [comment]
Add field for spacing before paragraph: no, small, med, lg, xlg..
See Call to Action Narrow for example already added.

**Comment by mwllr** [comment]
- [ ] Add field for spacing before paragraph: no, small, med, lg, xlg..See Call to Action Narrow for example already added.
- [x] on orange background, text should be white for sub title and body. 
- [x] on orange backgorund, the centering shows that the title is not centering when this is selected.
- [x] on blue background - need to have subtitle show as white text.
- [x] last example on page with white 2 paragraphs - align right, title doesn't align to the right.
- [ ] would still like to look at how is displays overall with the page width 
- [x] on mobile, need more spacing between buttons when they stack - maybe 20px?
- [x] on mobile - orange align left - the second button doesn't align left, seems indented.
- [x] on mobile - all background should expand 100% width of window. seems to have a 20px border of white.

![Screen Shot 2021-06-23 at 10 16 41 AM](https://user-images.githubusercontent.com/54747669/123123043-24fa1f80-d40c-11eb-9217-351b2f499646.png)
![Screen Shot 2021-06-23 at 10 16 29 AM](https://user-images.githubusercontent.com/54747669/123123044-2592b600-d40c-11eb-84b5-b26aca871b80.png)
![Screen Shot 2021-06-23 at 10 16 25 AM](https://user-images.githubusercontent.com/54747669/123123045-2592b600-d40c-11eb-9885-ca36a49686a3.png)
![Screen Shot 2021-06-23 at 10 13 20 AM](https://user-images.githubusercontent.com/54747669/123123047-2592b600-d40c-11eb-89fc-67f375044b5b.png)

**Comment by mwllr** [comment]
on drupal back end:

1. Add the spacing (none, s, m, lg...) as the very first thing.
2. Then move layout next, 
3. then: background, 
4. fingerprint, 
5. icon, 
6. title, (unless title has to come after subtitle to display correctly.)
7. subtitle, 
8. body, 
9. buttons. 

![Screen Shot 2021-06-24 at 1 01 16 PM](https://user-images.githubusercontent.com/54747669/123311368-ba6ce080-d4ec-11eb-9ab9-08c0ac731211.png)

**Comment by magjarvis** [comment]
Changes on latest push to git:

- CSS button styles for mobile: buttons will go full width on mobile, added 0.5rem of space between buttons
- Backend changes: rearranged form display to reflect above changes

**Comment by mwllr** [comment]
- [x] change font color to white on all orange backgrounds.
- [x] check button spacing/alignment on mobile. need vertical spacing between.
- [x] on gray background, change subtitle to blue instead of gray

**Comment by mwllr** [comment]
![Screen Shot 2021-07-12 at 4 30 23 PM](https://user-images.githubusercontent.com/54747669/125358552-a8819f00-e32e-11eb-9802-8cc7a0c0cdd3.png)

**Comment by lizshalley** [comment]
icon does not show up
![Screen Shot 2021-07-26 at 1 34 56 PM](https://user-images.githubusercontent.com/8646013/127040688-5571fb78-7436-44bb-a698-79979e4a17eb.png)

**Comment by mwllr** [comment]
- [ ] on orange gradient, subtitle needs to be white.  --  https://dev.ansc.illinois.edu/academics
- [ ] on mobile, buttons should not extend any bigger than they are on desktop or tablet.
- [ ] add common spacing between buttons: 30px
- [ ] when using icon, spacing needs fixed. icon should be right aligned to left of text.
- [ ] icons on blue gradient should be white, not orange.

**Comment by mwllr** [comment]
![Screen Shot 2021-08-02 at 4 01 56 PM](https://user-images.githubusercontent.com/54747669/127923403-d9412edd-58bd-4361-9a12-8708a628a3b1.png)

**Comment by mwllr** [comment]
![Screen Shot 2021-08-02 at 4 02 46 PM](https://user-images.githubusercontent.com/54747669/127923508-12ef4a9e-b3cf-45e0-a6df-1ed5c684e83d.png)

**Comment by mwllr** [comment]
![Screen Shot 2021-08-02 at 4 03 36 PM](https://user-images.githubusercontent.com/54747669/127923600-7632beed-2e41-4505-9ef9-ac9556287ef7.png)

**Comment by mwllr** [comment]
Closing and starting a new issue for all fixes needed.

**Comment by mwllr** [comment]
@trubach - I see you have a pull request on this though.... what do you need to do about that?

**Comment by trubach** [comment]
@mwllr - are you referring to #195? I had to do a bit of git cleanup before merging Maggie's branch. It's OK to ignore that. It's been merged and is included in the alpha.
