### ISSUE TITLE
Evaluate current sidebar placement methods

### ISSUE THREAD

**Issue by nbaxley-uiuc** [ATLAS-Illinois/Illinois-Framework-Theme#581]
We need to review the current method of placing the sidebar in a way that allows content to wrap around under it.  We should consider any changes that can be made to the page template and if we can move those changes to a content type specific template or not.

**Comment by nbaxley-uiuc** [comment]
One discussion topic was to create content type specific template files to handle the sidebar in content page different from other CTs.  As @robgasc pointed out, the "suggestion" method for template files is based on the URL.  There IS a way to suggest template files based on TYPE as [described here](https://befused.com/drupal/page-template-content-type/).  However, since the current Content Page CT template extends outside the main content and into the regions we might not be able to use it.

**Comment by robgasc** [comment]
This should also be addressed by https://github.com/web-illinois/illinois_framework_theme/issues/776, since it moves the generic page.html.twig to a generic solution of checking the sidebar. I'm going to close this out in lieu of that issue.
