### ISSUE TITLE
Illinois Framework Theme - Header Link List - Link #2 - Field Missing

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#583]
The link field for Link # 2 has run away.... Missing from the Framework theme as well as ACES theme when we went to RC 2.
![Screen Shot 2021-12-07 at 5 34 01 PM](https://user-images.githubusercontent.com/54747669/145122270-f5316f7c-7e39-4e62-a863-01540888b05a.png)

**Comment by wrg20** [comment]
Looks like a "t" is missing from the textfield

**Comment by wrg20** [comment]
Merge #586 fixes this issue
