### ISSUE TITLE
Rich Text and Content Page Body Image Padding/Margin/Alignment

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#589]
- [x] Left align images, add 20px padding to right of image, 25px bottom padding (already 10 there, change to 25).
- [x] Right align image - 20px padding on left, 25px bottom.
- [x] Get alignment to work on rich text

![Screen Shot 2022-01-27 at 1 04 53 PM](https://user-images.githubusercontent.com/54747669/151426813-2341e1de-d0f4-4b84-be0a-8ee72e8fbdf8.png)
![Screen Shot 2022-01-27 at 1 05 03 PM](https://user-images.githubusercontent.com/54747669/151426814-812a063e-6342-4b21-89e0-0f080a02fb3a.png)

NOTE - there is NO padding showing now! We need padding around the images. We need 25px. This is an older version.
![Screen Shot 2021-12-09 at 12 27 36 PM](https://user-images.githubusercontent.com/54747669/145454399-957c5a24-4115-43b6-9501-fe592ece68ac.png)

**Comment by wrg20** [comment]
merge #626 fixes this
