### ISSUE TITLE
Contact  - titles size/weight

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#599]
Change:
![Screen Shot 2022-01-05 at 4 02 22 PM](https://user-images.githubusercontent.com/54747669/148297609-b2b30147-3fba-4294-a710-f990a0b635d7.png)

TO:
section title- font size - 35, line height - 43, 600 weight, keep orange
contact title - font size - 29, line height - 35, 600 weight, keep blue
contact subtitle - font size - 25, line height - 29, 600 weight, keep gray
![Screen Shot 2022-01-05 at 4 03 20 PM](https://user-images.githubusercontent.com/54747669/148297603-80c0f1c9-371d-4fb0-be7a-a4963f3e5ccf.png)

**Comment by mwllr** [comment]
@magjarvis - do you have time to tackle this one? just a few size/weight tweaks?

**Comment by magjarvis** [comment]
@mwllr Sure, I can take this one

**Comment by nbaxley-uiuc** [comment]
@mwllr these changes are on the sandbox.  Can you review?

**Comment by mwllr** [comment]
Looks great!!
![Screen Shot 2022-01-07 at 4 27 32 PM](https://user-images.githubusercontent.com/54747669/148615486-dca6aedb-a8ac-483e-9983-679e5b730669.png)
