### ISSUE TITLE
Basic content editors need to add and edit tables

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#602]
Currently, basic editors can't even edit or add tables in rich text or the body of content pages. Can we get that feature added so they have that opportunity?

**Comment by nbaxley-uiuc** [comment]
I think we need to enable the table icons in the configuration settings.

**Comment by nbaxley-uiuc** [comment]
@nbaxley-uiuc will review current configurations

**Comment by mwllr** [comment]
Added option for users to add and edit tables in ck editor.
