### ISSUE TITLE
Accordion - left margin needs aligned

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#604]
when accordions are not next to sidebar, they are not aligned with page margins. They stick out to left too much. 
![Screen Shot 2022-01-06 at 3 52 00 PM](https://user-images.githubusercontent.com/54747669/148457384-c2f32757-4ff7-429c-a270-943d2cbae31d.png)

**Comment by mwllr** [comment]
@magjarvis or @robgasc ??

**Comment by trubach** [comment]
Page with an example of the issue: https://illinois-drupal.web.illinois.edu/paragraphs/accordion
