### ISSUE TITLE
Media render not working in rich text paragraph body

### ISSUE THREAD

**Issue by robgasc** [ATLAS-Illinois/Illinois-Framework-Theme#605]
Basically, same issue as with content pages body rendering, where we are using `content.field_rt_column[loop.index0]['#paragraph'].field_rt_content_body.value and body | raw` in paragraph--rt.html.twig in the theme. Need to identify the right twig tweaks function to render a body field in a parent paragraph for a referenced paragraph's field.

Alternatively, convert this single template handling the rendering to a template to render the referenced paragraph (rich text content) and then one for the referencing field to get count of items switch for columns in place, so we don't have to use the twig tweaks function.

First mention of issue is https://github.com/web-illinois/illinois_framework_theme/issues/534 by @mwllr

**Comment by nbaxley-uiuc** [comment]
Should resolve #618 and #411

**Comment by wrg20** [comment]
merge #645 should fix this issue

**Comment by wrg20** [comment]
got all media to display except for remote video

**Comment by wrg20** [comment]
Video embed module was not installed so the video button was not being pulled in properly.  Configuration will need to be added to enable this module.

**Comment by robgasc** [comment]
Not quite sure what you mean, Bill. Seems the remote video is working fine now in Rich Text. There should not be any more pieces of that video embed field module enabled than are enabled now, that separate button is primarily to allow Mediaspace videos, not anything to do with the Media library.

**Comment by wrg20** [comment]
@robgasc - just realized it was a issue with the text filter not with the module.

**Comment by wrg20** [comment]
submitting for testing...

**Comment by nbaxley-uiuc** [comment]
Looks good to me!
