### ISSUE TITLE
Clickable Cards (Big Buttons) Paragraph Type

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#61]
![image](https://user-images.githubusercontent.com/1544079/114627537-0690de80-9c7b-11eb-9255-5ef892643afc.png)

**Comment by wrg20** [comment]
only 1 option. white with focus/hover to illini blue.

**Comment by wrg20** [comment]
Done with Merge #65

**Comment by wrg20** [comment]
body not required.

**Comment by wrg20** [comment]
Need to rename this to something like cards because "button" indicates that it is actually a button html element.

**Comment by mwllr** [comment]
Change h2 line -height to 1.75 rem

**Comment by mwllr** [comment]
Add field for spacing before paragraph: no, small, med, lg, xlg..
See Call to Action Narrow for example already added.

**Comment by lizshalley** [comment]
Turn off *Required for body text, this should be optional.

**Comment by mwllr** [comment]
Add additional background color - gray.

**Comment by mwllr** [comment]
- [ ] Change h2 line -height to 1.75 rem
- [x] Add field for spacing before paragraph: no, small, med, lg, xlg.. See Call to Action Narrow for example already added.
- [x] Body text should be optional, not required. 
- [x] Add additional background color - gray.
- [x] Add an option for a heading/title for section - option to select left, right, center aligned.
- [x] Add double chevron after h2 [see zeplin example](https://zpl.io/VKdgnyq)
- [x] Add title/subtitle options for the paragraph section

**Comment by magjarvis** [comment]
FYI, working on above edits for this paragraph

**Comment by magjarvis** [comment]
pushed edits to git, I might need @wrg20 to help with adding an if statement to the twig file that will only show the body field when it has a value
