### ISSUE TITLE
Move to Components 2.5

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#617]
- [ ] Update component include to point to version 2.5

**Comment by nbaxley-uiuc** [comment]
@mwllr Is this just about changing the toolkit version we point to so that people can manually use the features in 2.5 or actually build components for all of them?

**Comment by mwllr** [comment]
@nbaxley-uiuc There are no new components in 2.5 - only font spacing and sizing changes. Want to change to use on template, not just to build things.
