### ISSUE TITLE
Rich Text - Images, Video, and PDFs/Media Library

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#618]
Trying to add images, video and pdfs to the body and to a rich text.

- [x] Rich text - Adding image via image icon in ckeditor - works great. - REMOVING THIS OPTION IN CK EDITOR
- [x] Rich text - Adding via video embed icon in ckeditor: - only code displays
- [x] Rich text - Adding via insert from Media Library icon in ckeditor-- Video: nothing displays
- [x] Rich text - Adding via insert from Media Library icon in ckeditor-- Remote Video: nothing displays
- [x] Rich text - Adding via insert from Media Library icon in ckeditor-- Document: nothing displays
- [x] Rich text - Adding via insert from Media Library icon in ckeditor-- Image: nothing displays

https://illinois-drupal.web.illinois.edu/paragraphs/rich-text/rich-text-image-video-pdf-media-library

**Comment by nbaxley-uiuc** [comment]
@mwllr It looks like some of these are working in the page you linked to and some are not.  Can you clarify?

**Comment by wrg20** [comment]
merge #645 should fix this issue

**Comment by wrg20** [comment]
merge #649 media embed fixed

**Comment by wrg20** [comment]
I believe the media module is only setup on the basic html text format....as long as you use basic all of the types of media should display properly.  Needs testing.
