### ISSUE TITLE
Content Page - Body - Image display

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#619]
Trying to add images, video and pdfs to the body and to a rich text. In Body, all options work, although first image via image icon in ckeditor is whacked out.

- [ ] Remove the first, "direct" image embed option from the text editor in favor of the media library

https://illinois-drupal.web.illinois.edu/paragraphs/rich-text/rich-text-image-video-pdf-media-library

**Comment by nbaxley-uiuc** [comment]
The image problem is because that first icon just drops the image in at whatever size it is.  Maybe we need to just remove that option in favor of the media library.

**Comment by nbaxley-uiuc** [comment]
Decided to remove the first image embed icon and use the Media Library embed only.
