### ISSUE TITLE
Add content adjustment javaScript to page--news template

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#620]
Using a paragraph on the news page along with a sidebar results in the columns not displaying properly.
![image](https://user-images.githubusercontent.com/1544079/151612407-cb4b2a36-cce1-46bb-af8b-6a4e1213e5da.png)

**Comment by nbaxley-uiuc** [comment]
Is it the gap at the top that's the problem?
