### ISSUE TITLE
Fix the padding on images in rich text body fields

### ISSUE THREAD

**Issue by nbaxley-uiuc** [ATLAS-Illinois/Illinois-Framework-Theme#626]
Needs to be fixed for both node body text and the rich text paragraph.

**Comment by wrg20** [comment]
merge #653 should fix this issue

**Comment by mwllr** [comment]
Looks great!
![Screen Shot 2022-03-04 at 9 46 25 AM](https://user-images.githubusercontent.com/54747669/156794884-3622415c-fc4d-4e2a-8c98-9d092eed5d65.png)
