### ISSUE TITLE
Adding breadcrumbs and styling

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#628]
We should go ahead and add breadcrumbs to the content pages. 

- [x] Apply correct styling as listed here: https://xd.adobe.com/view/774499da-8370-42db-a7da-bf208652c967-2217/
- [x] Remove breadcrumbs on mobile and tablet

**Comment by wrg20** [comment]
merge #672 adds the breadcrumb styling

**Comment by wrg20** [comment]
font size 14px

**Comment by mwllr** [comment]
@wrg20 - need breadcrumbs to show parent sections in addition to home and page titles.
also need to fix spacing between breadcrumb and page title. remove some.

https://xd.adobe.com/view/774499da-8370-42db-a7da-bf208652c967-2217/screen/45508b44-e6e8-49fb-9c69-4cc7e1e4b866/specs/

**Comment by wrg20** [comment]
@mwllr - ready for review

**Comment by mwllr** [comment]
@wrg20 Looks great and functions well with exception on not quite working right if you switch a page from manual to auto URL assigning. 
I change the page name and clicked auto URL on and it still shows as the old title in the breadcrumbs.?
https://illinois-drupal.web.illinois.edu/paragraphs

**Comment by mwllr** [comment]
Applied and styled as directed. Great.
![Screen Shot 2022-05-04 at 11 46 34 AM](https://user-images.githubusercontent.com/54747669/166732214-36544eb2-0662-44c1-8c62-c02ceff0b062.png)
