### ISSUE TITLE
Create new content type - landing page

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#629]
Mimicking the content page we have with the following changes:

- [ ] no breadcrumbs
- [ ] no page title displaying (must use a hero to do this)
- [ ] no side navigation 

@nbaxley-uiuc or  @magjarvis - what else would you want for this landing page content type?

**Comment by mwllr** [comment]
@magjarvis  and @trubach  - do we still need this since we changed a bunch around to accommodate landing pages?

**Comment by trubach** [comment]
The functionality already built-in with the framework allows for landing pages to be created. I created a new issue to document how to create a landing page at #857.
