### ISSUE TITLE
Menu - check right align on mobile due to components 2.4 upgrade

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#630]
NOTE: This is in the toolkit components. Will be fixed there... Not our issue. The components team is aware and working on it.

added align=right to the component code in components 2.4
adds text-align = right but doesn't remove it on the small breakpoint
![Screen Shot 2022-02-03 at 9 35 08 AM](https://user-images.githubusercontent.com/54747669/152384835-a1417dfd-3357-4813-aac1-d806b2e8a7ea.png)
![Screen Shot 2022-02-03 at 9 35 27 AM](https://user-images.githubusercontent.com/54747669/152384846-1bc621e8-391a-4d9f-a2d0-f5b1e968ae05.png)
![Screen Shot 2022-02-03 at 9 36 15 AM](https://user-images.githubusercontent.com/54747669/152384848-a33a0191-54dd-4957-ac77-4a45878068f7.png)

**Comment by wrg20** [comment]
@mwllr - this should be fixed when we update to 2.2 because 2.5+ of the toolkit is installed with it.
