### ISSUE TITLE
Content Page - margins on mobile

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#634]
- [ ] on mobile - we lose the 20px left and right margin. Missing on side navigation, body, paragraphs, etc... under 575px window size.
- [x] Also affects paragraphs next to side navigation.

Example: https://illinois-drupal.web.illinois.edu/paragraphs/feature-box
![Screen Shot 2022-02-08 at 4 42 03 PM](https://user-images.githubusercontent.com/54747669/153087915-5344bb12-537a-4ba8-b9d6-55caa0d76a6b.png)

Example: https://cropsciences.illinois.edu/academics/undergraduate-degrees
![Screen Shot 2022-02-08 at 4 42 55 PM](https://user-images.githubusercontent.com/54747669/153087993-cc2f8a3a-8cc2-47e8-a89c-468ec5523fc1.png)

**Comment by wrg20** [comment]
merge #659 should fix this

**Comment by nbaxley-uiuc** [comment]
@wrg20 I tested this with the two examples @mwllr gave.  The [first one ](https://illinois-drupal.web.illinois.edu/paragraphs/feature-box) seems to be working, but in the [Crop Sci example ](https://cropsciences.illinois.edu/academics/undergraduate-degrees) there's still no left margin on mobile.  Not a deal breaker, but if we can get it corrected maybe it can go out in a 2.1.1 or 2.2 at the latest.

**Comment by mwllr** [comment]
Looks great!. content margins fixed.
