### ISSUE TITLE
Video Element constrained to original video width

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#646]

**Comment by wrg20** [comment]
the video element when inserted using media constrains the video to the original width, this is as designed by the system

**Comment by wrg20** [comment]
https://www.drupal.org/forum/support/post-installation/2020-12-22/adjust-remote-video-embed-dimensions

Here is the behavior.

**Comment by wrg20** [comment]
I can't seem to reproduce this issue now

**Comment by mwllr** [comment]
![Image](https://github.com/web-illinois/illinois_framework_theme/assets/54747669/bf74f662-bd92-4548-ac3c-7ddac78bee55)

**Comment by trubach** [comment]
Closing due to lack of new comments and no example pages
