### ISSUE TITLE
Big button mobile

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#662]

**Comment by wrg20** [comment]
![image](https://user-images.githubusercontent.com/1544079/156391573-244a11af-5a9d-4ef8-96e2-3af237e408e7.png)

Adjust the padding and margins on mobile

**Comment by magjarvis** [comment]
@mwllr what should the correct margin/padding be for mobile?

**Comment by magjarvis** [comment]
This should be resolved
