### ISSUE TITLE
Padding below "in this section"

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#678]
![image](https://user-images.githubusercontent.com/1544079/157587049-ffd070b9-ff75-431c-9642-cafca931e39d.png)

Looks like padding is needed below the "In this section" drop down list.  @mwllr

**Comment by wrg20** [comment]
@mwllr - how much padding do you want?  I'm going to add 10px...

**Comment by wrg20** [comment]
![image](https://user-images.githubusercontent.com/1544079/162326824-0085ec64-eee7-4342-9f1b-45ff47dc785e.png)

**Comment by mwllr** [comment]
@wrg20 
![Screen Shot 2022-04-11 at 5 29 35 PM](https://user-images.githubusercontent.com/54747669/162843835-f8944103-c47c-4cc5-8700-b06cd3d3ad78.png)

**Comment by mwllr** [comment]
in page layout xd doc : https://xd.adobe.com/view/958c679e-b8a7-44df-aa45-5c6ba543b082-c0df/

**Comment by mwllr** [comment]
@wrg20 remove 10px please.

**Comment by wrg20** [comment]
remove 10px from the bottom of the "in this section"

**Comment by wrg20** [comment]
@mwllr - removed the 10px below the "in this section"

**Comment by mwllr** [comment]
@wrg20 - can you remove 20px **ABOVE** in this section?

**Comment by mwllr** [comment]
Looks great
![Screen Shot 2022-05-05 at 1 22 51 PM](https://user-images.githubusercontent.com/54747669/166989825-66565c7f-ebf3-4e9a-84b8-1f12054176ed.png)
.
