### ISSUE TITLE
Fix formatting on any menu block in the sidebar region

### ISSUE THREAD

**Issue by nbaxley-uiuc** [ATLAS-Illinois/Illinois-Framework-Theme#680]
Add the new template that was created for the ESL site to gain the extra styling.

**Comment by mwllr** [comment]
@robgasc - where are we at on this issue??? have you started?

**Comment by robgasc** [comment]
@mwllr There are pieces in our subtheme that fix this menu block issue, but I don't have time to get them added to the main framework before the release. Think this needs to be bumped to 2.3.

**Comment by robgasc** [comment]
The issue https://github.com/web-illinois/illinois_framework_theme/issues/776 should address this as well. Closing this as a duplicate.
