### ISSUE TITLE
Drupal documentation - create a custom blocks/blocks section

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#688]
@mwllr - It may be worthwhile to create a custom blocks/blocks section to the illinois drupal (https://drupal.webtheme.illinois.edu) website.  So we can see the block behavior of all of our views blocks / custom blocks.

_Originally posted by @wrg20 in https://github.com/web-illinois/illinois_framework_theme/issues/671#issuecomment-1072788701_

**Comment by mwllr** [comment]
@wrg20 - I'd be happy to help with this if I knew which blocks we needed to add to pages for documentation. 
@magjarvis  - do you know any blocks for this?

-highlighted news blocks are the original reference. others?

**Comment by magjarvis** [comment]
@mwllr we used custom blocks for our department headers? not sure if those would count, but it was helpful to us and we were able to use the page header component with it.

Hover box news might also be something to document

**Comment by mwllr** [comment]
There's a page already added for highlighted news - 
https://drupal.webtheme.illinois.edu/highlighted-news
@wrg20  - what else should be there??
