### ISSUE TITLE
List Collection Title/Subtitle padding

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#689]
- 60 above title/subtitle then 30 above content
- if there is no title/subtitle it should still be 60 (60 above content)

**Comment by mwllr** [comment]
@wrg20 - looking at sandbox this morning and the spacing at the beginning of the paragraph looks good, but now, I lost the padding on the images.
And there should be 50px between the title and subtitle.

**Comment by wrg20** [comment]
Yes there were a few field misspelled in the twig template.  I'm guessing changing those affected the layout.  I'll take a look.

**Comment by wrg20** [comment]
![image](https://user-images.githubusercontent.com/1544079/163224772-86349a79-e67a-4dff-8e09-dd1dfc3972f6.png)

**Comment by wrg20** [comment]
https://cdn.toolkit.illinois.edu/2/examples/stylesheets/typography/headings/index.html

See h2/h3 from toolkit

**Comment by wrg20** [comment]
I believe Maggie was working on changing the subtitle to a field instead of an h3.

**Comment by mwllr** [comment]
@wrg20  - can we get spacing between the headings if both are used? Currently, there isn't any/enough.
![Screen Shot 2022-05-04 at 11 44 54 AM](https://user-images.githubusercontent.com/54747669/166731274-d7f6a560-6b39-4b06-8733-005cbe96cba8.png)

**Comment by mwllr** [comment]
Looks great.
![Screen Shot 2022-05-05 at 1 23 27 PM](https://user-images.githubusercontent.com/54747669/166990164-bb91fb04-0e6f-45ac-885f-01cfa6156648.png)
