### ISSUE TITLE
Nolink in sidebar 

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#702]
A "\<nolink\>" in the menu structure doesn't have the proper padding / formatting for the sidebar

![image](https://user-images.githubusercontent.com/1544079/163262860-9047427e-10dc-4702-9879-e2d70917a38d.png)

**Comment by mwllr** [comment]
This was fixed in toolkit - 2.13.1

**Comment by wrg20** [comment]
Tested in 2.14.0 and it works.  2.13.1 wouldn't load from cdn.toolkit.  So when we update to 2.14.0.

**Comment by wrg20** [comment]
We will need to update illinois-drupal with 2.14 to test it out first...asking Tyler to see if we can make the change

**Comment by trubach** [comment]
This should be fixed when #869 (upgrade toolkit to 2.14) is closed
