### ISSUE TITLE
Need spacing on basic page with just body content

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#703]
![image](https://user-images.githubusercontent.com/1544079/163264930-196ddbe1-91bd-45fc-b1d4-a1bf9234fb34.png)

**Comment by wrg20** [comment]
Remove the repeating classes on the field body twig file.  Then add the 60px top and 75px bottom padding.

![image](https://user-images.githubusercontent.com/1544079/163461250-03db722e-16b5-434d-84d0-2111da0a3be2.png)

**Comment by mwllr** [comment]
body now has bottom padding.
