### ISSUE TITLE
Conflicting Button Colors on toolkit 2.7

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#710]
When the 2.7 toolkit is used there is a conflict with the buttons.  The href attribute is also not getting pulled in properly into the component code (\<a class="il-button"\>).
![image](https://user-images.githubusercontent.com/1544079/163585152-31500624-1613-4d6b-84aa-13e4d640c4c4.png)

![image](https://user-images.githubusercontent.com/1544079/163585435-d760a456-18e9-4c76-9b52-f1576284384c.png)

**Comment by mwllr** [comment]
@wrg20 - look at now that we are using 2.10 to see if resolved.

**Comment by mwllr** [comment]
https://staging.aces.illinois.edu/admissions/future-students

**Comment by mwllr** [comment]
Here are the basic theme rules if this helps for button colors
https://xd.adobe.com/view/0497320b-2819-4826-836d-a78502dce926-51c4/
@wrg20
