### ISSUE TITLE
first paragraph - override toolkit css for first child p margin

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#711]
- [x] override toolkit css for first child p margin
- [x] add top and bottom margins - 60 and 75.
- [x] when stacking white and white, remove padding from bottom of first and top of second. add 40 px of padding.

(will come back later and reformat entire rich text/il-formatted sections)

**Comment by wrg20** [comment]
Tons of these paragraphs don't have the proper padding on the top and bottom.  Should I add 60px and 75px to all paragraphs by default?  I can't adjust the padding based on background color because they all have different padding. @mwllr

**Comment by wrg20** [comment]
`jQuery(function ($) {
  ($(".paragraph").find(".background--color--white")).each(function(){
    console.log('has white');
  });
});`

**Comment by wrg20** [comment]
The p child element is now fixed due to adding il-formatted to our body

**Comment by wrg20** [comment]
merge #742 should fix the padding, please test @mwllr

**Comment by wrg20** [comment]
![image](https://user-images.githubusercontent.com/1544079/166006389-8165bdb8-ca5e-4d50-b008-ef45625eb0fb.png)

**Comment by wrg20** [comment]
- [x] Rich Text Body margin bottom remove
- [x] CTA extra padding remove from wrapper
- [x] Remove border from feature boxed
- [x] Remove top/bottom padding for feature box, feature video, feature split
- [x] Do check on Big Buttons title
- [x] Icon row background programmed wrong

**Comment by wrg20** [comment]
- [x] Remove 75px of padding from last paragraph next to sidebar
