### ISSUE TITLE
Hero needs negative top margin

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#714]
hero needs -20px top margin now that we added to the main content margin
![Screen Shot 2022-04-19 at 10 25 34 AM](https://user-images.githubusercontent.com/54747669/164039953-d29e6a9f-3663-43c6-b7bb-e452f9fa18cd.png)

**Comment by wrg20** [comment]
Merge #735 should fix this issue. Hopefully no one tries to put a hero image anywhere other than the top of their page.

**Comment by wrg20** [comment]
Merge #763 makes the margin !important to override all margins

**Comment by wrg20** [comment]
@mwllr - test it out now
