### ISSUE TITLE
Featured Boxed next to sidebar

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#726]
The feature boxed next to the sidebar displays improperly.
![image](https://user-images.githubusercontent.com/1544079/164548538-381987c0-771d-4328-b6a4-43eace8e3f65.png)

**Comment by wrg20** [comment]
![image](https://user-images.githubusercontent.com/1544079/164548947-6207d969-09ac-4ed8-a939-1982f3649609.png)

small breakpoint

**Comment by wrg20** [comment]
merge #733 fixes the issues on mobile.

**Comment by mwllr** [comment]
Can we match the margin on text in the box and the break points to builder?
https://builder.toolkit.illinois.edu/prod/image-feature-preview/index.html
