### ISSUE TITLE
Rich Text Paragraph 

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#73]
Create a two column options with a main title and option for a title in each column.

- 1 column version will be 10 columns wide
- 2 column version will be 12 columns wide
- The paragraph will be constrained to a fixed container width
- The background will be only white at this time with no other options

**Comment by wrg20** [comment]
Created the rich text paragraph with merge #75

**Comment by mwllr** [comment]
Add field for spacing before paragraph: no, small, med, lg, xlg..
See Call to Action Narrow for example already added.

**Comment by mwllr** [comment]
- [ ] Add field for spacing before no, small, med, lg... - see call to action narrow for example.
- [ ] one column of text shouldn't go wider than 900 pixels wide and should be centered.
- [ ] two columns can go to 1200px wide max. and should stack when they are smaller than 600px.
- [ ] Add option for gray background 100% of screen width. #f4f4f4 is gray background color.

**Comment by lizshalley** [comment]
mobile version needs smaller margins/padding.

![Test - Rich Text  Animal Sciences  University of Illinois](https://user-images.githubusercontent.com/8646013/124295836-e99fd500-db1e-11eb-84f6-f473defd7050.jpeg)

**Comment by lizshalley** [comment]
on tablet, 2 columns should stack.
![Screen Shot 2021-07-07 at 11 24 29 AM](https://user-images.githubusercontent.com/8646013/124795865-26503f80-df16-11eb-8ff6-94994aeeb9e9.png)

**Comment by mwllr** [comment]
- [ ] two columns can go to 1200px wide max. 
- [ ] two columns should stack when they are smaller than 600px.
- [ ] Add option for gray background 100% of screen width. #f4f4f4 is gray background color.
- [ ] mobile - margins/padding should match header - 15 or 30 I believe.
- [ ] add alignment option for titles - left or center
- [ ] add alignment option for whole section - left or center
- [ ] fixed and full are for background.
- [ ] add option for text to be 900 pixels or 1140 pixels wide for max width.

**Comment by wrg20** [comment]
The above settings just don't present a realistic programmable set of options and present a user experience problem.  For example: Someone sets side navigation with 1400 max width text with left aligned titles with 2 columns, left section centering, large margins.  What do we do with this?  The layout should really dictate the margins/padding/text width instead of the user.

**Comment by mwllr** [comment]
let's leave these off for now:
- [x] two columns can go to 1200px wide max. 
- [x] add option for text to be 900 pixels or 1140 pixels wide for max width.

**Comment by mwllr** [comment]
- [ ] two columns should stack when they are smaller than 600px.
- [ ] Add option for gray background 100% of screen width. #f4f4f4 is gray background color.
- [ ] mobile - margins/padding should match header - 15 or 30 I believe.
- [ ] add alignment option for titles - left or center
- [ ] add alignment option for whole section - left or center
- [ ] fixed and full are for background.
- [ ] Add s, m, l, drop down list for margin/padding before the paragraph like other ones..
- [ ] when rich text on staff page, needs to align left with page title. https://staging.ansc.illinois.edu/directory/staff
- [ ] Add "pretty" anchor link option. ability for me to put in advising for example, then go to page xyz#advising.

**Comment by mwllr** [comment]
closing - opened new cleaned up ticket.
