### ISSUE TITLE
Use media for all image fields

### ISSUE THREAD

**Issue by robgasc** [ATLAS-Illinois/Illinois-Framework-Theme#755]
Some paragraphs (Cards, Buttons) use image fields instead of media fields. This results in confusion for users as the fields operate differently and discourages reuse of existing images/content.

Steps:

1. Identify image/file/video fields.
2. Add a parallel media field.
3. Write update hook to deploy this change for existing sites, including migrating image from old field to new field. (need a batch script of some kind to convert between the old field and new, make a media item, etc.)
4. Update templates to use the new field. 
5. Delete old field.

Step 1:

- field_bb_content_image | paragraph | Image (module: image) | Big Buttons Content
- field_cards_content_image | paragraph | Image (module: image) | Cards Content
- field_contact_content_image | paragraph | Image (module: image) Contact Content
- field_cta_icon | paragraph | Image (module: image) | Call to Action
- field_feature_boxed_img | paragraph | Image (module: image) | Feature Box
- field_feature_grouped_image | paragraph | Image (module: image) | Feature Group
- field_feature_split_img | paragraph | Image (module: image) | Feature Split
- field_hero_image | paragraph | Image (module: image) | Hero
- field_list_content_image | paragraph | Image (module: image) | List Collection Content

**Comment by trubach** [comment]
Closing due to no movement. If we want to revisit this, we can reopen this issue, or create separate issues for each field/paragraph that needs to be converted.
