### ISSUE TITLE
Background color needs to be changed to Gray

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#769]

**Comment by wrg20** [comment]
The feature grouped background config shows as grey instead of gray
![image](https://user-images.githubusercontent.com/1544079/167030090-43e39384-cfb2-4b4f-9572-8bf2457c86f5.png)

**Comment by wrg20** [comment]
@mwllr - what do we want to do with this one? I need to fix the configuration for it to display gray instead of grey for the background color or change one line of CSS

  ```
&--gray,
  &--grey {  //add this line?
    background-color: #f4f4f4;
    width: 100%;

    .body {
      a {
        &:link {
          color: var(--il-alma-mater);
        }
        &:visited {
          color: var(--il-alma-mater-1);
        }
        &:hover,
        &:focus {
          color: var(--il-industrial-blue);
        }
      }
      p {
        color: $body-color;
      }
    }
    h1,h2,h3,h4,h5,h6 {
      color: var(--il-blue);
    }
```

**Comment by wrg20** [comment]
Grey is British English while Gray is American English

**Comment by mwllr** [comment]
GRAY!

**Comment by wrg20** [comment]
Changed the label and submitted a pull request on the drupal core repo.  https://github.com/web-illinois/illinois_framework_core/pull/83

**Comment by wrg20** [comment]
@trubach - I've submitted a pull request for you to review.

**Comment by wrg20** [comment]
Was reviewed and merged with another git issue.
