### ISSUE TITLE
list collection requires Section Title or it will not show

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#770]
![image](https://user-images.githubusercontent.com/1544079/167708622-17785d67-7f24-43af-9977-3f0a355b4444.png)

If the Section Title does not exist then the list collection will not show up.

**Comment by mwllr** [comment]
I think this is done. I just added a new list collection to sandbox without title or subtitle and it displays.
https://illinois-drupal.web.illinois.edu/paragraphs/list-collection
@magjarvis  - can you verify/confirm? If good to go, close this issue, please.

**Comment by magjarvis** [comment]
Closing, works without title
