### ISSUE TITLE
When body empty, strip_tags function gets null for big button paragraph

### ISSUE THREAD

**Issue by robgasc** [ATLAS-Illinois/Illinois-Framework-Theme#772]
Produces `Warning: strip_tags() expects parameter 1 to be string, array given in twig_striptags()`

Only happens when the body is left empty for big buttons. Need to check if field is empty before rendering it in the template.

**Comment by mwllr** [comment]
@wrg20 or @trubach - this was fixed with the last release, correct?

**Comment by trubach** [comment]
Yes, this was fixed in PR #860
