### ISSUE TITLE
spacing between h1 and first specialty content 

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#803]
spacing when big buttons was the only thing on the page

**Comment by mwllr** [comment]
![Screen Shot 2022-11-16 at 11 08 25 AM](https://user-images.githubusercontent.com/54747669/202246818-b53f1869-f62d-41b6-92bb-17102820bc30.png)

**Comment by trubach** [comment]
Tracking in issue #988
