### ISSUE TITLE
Rich Text paragraph title spacing to body

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#804]
Happens on both Gray and White.

**Comment by mwllr** [comment]
https://staging.aces.illinois.edu/academics/undergraduate-degrees

**Comment by wrg20** [comment]
title should have 15px spacing before body or subtitle

**Comment by wrg20** [comment]
added 15px of margin to the bottom of the h2 element for the rich text.  toolkit has 0px margin
