### ISSUE TITLE
Change all H2s to orange

### ISSUE THREAD

**Issue by magjarvis** [ATLAS-Illinois/Illinois-Framework-Theme#806]
- [ ] add new orange to h2
- [ ] add new altgeld to h2 on gray

**Comment by magjarvis** [comment]
@mwllr For H2 styles coming in from the toolkit, should I put in a ticket with the toolkit folks or do I need to override the toolkit styles? Most of our paragraph styles have il-orange/altgeld H2s where appropriate, but H2 styles coming from the toolkit are still il-blue

**Comment by mwllr** [comment]
Reevaluating the orange headings for text due to the gray sections needing altgeld - https://illinois-drupal.web.illinois.edu/paragraphs/rich-text/rich-text-2 I almost want to leave them as blue now and only use the orange headings for specialty paragraphs? What do you think @magjarvis ?

**Comment by mwllr** [comment]
cancelling this for rich text. We will still use some orange headings in our specialty paragraph types.
