### ISSUE TITLE
WYSIWYG image does not align center

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#807]

**Comment by trubach** [comment]
Images using the "Center" alignment with the WYSIWYG editor don't display centered when viewing the page. Example:

![image](https://github.com/web-illinois/illinois_framework_theme/assets/56594946/75814fe6-21c0-4c9b-a26c-9bc6dd81e212)

Issue can be seen on bottom of this page: https://ddevwebtheme.web.illinois.edu/paragraphs/rich-text
