### ISSUE TITLE
add visible-hidden text to social media icons in footer

### ISSUE THREAD

**Issue by Detzner** [ATLAS-Illinois/Illinois-Framework-Theme#822]
in templates > region > region—footer.html.twig, add visible-hidden text label to social media icons in footer, lines 59 - 71 (<span class="visible-hidden">Instagram</span>), have to insert text because icons are font-based, not images where you could put an alt tag

**Comment by wrg20** [comment]
Per the toolkit...https://cdn.brand.illinois.edu/toolkit/2.10/examples/components/footer/default/index.html it appears that the text is within the anchor tag for each social media icon.

**Comment by wrg20** [comment]
@Detzner - please review the merge #852.

**Comment by Detzner** [comment]
Hi Bill—

I was off today, just back from out of town, but will look at this first thing tomorrow.

Dick

From: William Gutierrez ***@***.***>
Date: Monday, September 19, 2022 at 12:49 PM
To: web-illinois/illinois_framework_theme ***@***.***>
Cc: Detzner, Richard ***@***.***>, Mention ***@***.***>
Subject: Re: [web-illinois/illinois_framework_theme] add visible-hidden text to social media icons in footer (Issue #822)

@Detzner<https://urldefense.com/v3/__https:/github.com/Detzner__;!!DZ3fjg!4XwWGK0OKZOMn8RDnBN8yq7kV3XLASD5-VmMBXpiwoPowNYxvpI-389E2qbGn6s7t5XT20xi3sYtaUytyghGdYc1F-4$> - please review the merge #852<https://urldefense.com/v3/__https:/github.com/web-illinois/illinois_framework_theme/pull/852__;!!DZ3fjg!4XwWGK0OKZOMn8RDnBN8yq7kV3XLASD5-VmMBXpiwoPowNYxvpI-389E2qbGn6s7t5XT20xi3sYtaUytyghGVBCuC78$>.

**Comment by wrg20** [comment]
Per Teams conversation.  I will add the markup @Detzner - Thank you!  I'll let you know when it's ready to look at again here shortly.

**Comment by mwllr** [comment]
@Detzner  - can you verify this is fixed? if so, close with a comment.

**Comment by Detzner** [comment]
Yes, this is fixed. Thanks!
