### ISSUE TITLE
ACES Faculty Explorer paragraph type

### ISSUE THREAD

**Issue by NotThatDavidCross** [ATLAS-Illinois/Illinois-Framework-Theme#83]
Create Faculty Explorer paragraph type for ACES

**Comment by mwllr** [comment]
Add field for spacing before paragraph: no, small, med, lg, xlg..
See Call to Action Narrow for example already added.

**Comment by mwllr** [comment]
department explorers are used on home, future, visit and are all full width.
directory explorer is used both full and with side nav.
Grad Degree are always full width.

**Comment by mwllr** [comment]
- [ ] department explorer (used on home page) - top padding - 60px, bottom padding 75px. remove padding for the results so it butts up to the split feature below.
![Screen Shot 2021-08-09 at 3 41 58 PM](https://user-images.githubusercontent.com/54747669/128772379-e2706553-45de-407b-9887-36f76eb8992d.png)

**Comment by mwllr** [comment]
https://cdn.brand.illinois.edu/toolkit/dev/examples/stylesheets/formatting/index.html

![Screen Shot 2021-08-10 at 12 23 38 PM](https://user-images.githubusercontent.com/54747669/128906874-f3296634-89ac-47ea-8e35-9159025542fb.png)

**Comment by NotThatDavidCross** [comment]
Spacing changes ready for review

**Comment by NotThatDavidCross** [comment]
Add "No faculty for this combination" text when there are no results for a combination

**Comment by mwllr** [comment]
@NotThatDavidCross - I assume you know Anna Dilger shows up in all categories and there isn't "No faculty for this combination" text when there are no results for a combination.... yet.

**Comment by mwllr** [comment]
closing this to move to ACES repository as needed.
