### ISSUE TITLE
Hero buttons showing visited state

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#845]
Override toolkit code so we don't see visited buttons in the hero.

**Comment by mwllr** [comment]
issues on mobile and desktop in chrome

Mobile:
![Screen Shot 2022-09-08 at 11 30 10 PM](https://user-images.githubusercontent.com/54747669/189432741-ce2a45f3-a038-4774-bf7f-15853d0def65.png)

**Comment by mwllr** [comment]
desktop/tablet:
![Screen Shot 2022-09-07 at 4 55 33 PM](https://user-images.githubusercontent.com/54747669/189434016-28f4e0fd-de10-4adb-b1f5-f17caaea671b.png)

**Comment by wrg20** [comment]
Merge #850  should fix this.  Please review @mwllr

**Comment by mwllr** [comment]
Visited buttons are fixed.
