### ISSUE TITLE
Document how to create a landing page and how to set the homepage

### ISSUE THREAD

**Issue by trubach** [ATLAS-Illinois/Illinois-Framework-Theme#857]
We need to create some documentation on how to create landing pages by hiding the page title in the block visibility settings.

![image](https://user-images.githubusercontent.com/56594946/194649719-3b85d5b9-f42f-4488-bb66-edbdf9b07246.png)

Maybe create 'Creating a landing page' and 'Setting the homepage' pages in the 'Site setup' section of the https://drupal.webtheme.illinois.edu/ website.

**Comment by mwllr** [comment]
Page added - https://drupal.webtheme.illinois.edu/site-setup/landing-page
Setting the front page is already in basic site settings - https://drupal.webtheme.illinois.edu/site-setup/basic-site-settings
