### ISSUE TITLE
Title showing outside main content

### ISSUE THREAD

**Issue by magjarvis** [ATLAS-Illinois/Illinois-Framework-Theme#873]
Page title is displaying outside the main content region and above the sidebar. Not sure if this is because we aren't using breadcrumbs on these sites or what is happening

**Comment by magjarvis** [comment]
<img width="995" alt="Screenshot 2022-12-08 153614" src="https://user-images.githubusercontent.com/8452264/206573008-2c9f01cd-bb3f-4d9f-9f44-b16daddaefd2.png">
<img width="979" alt="Screenshot 2022-12-08 153643" src="https://user-images.githubusercontent.com/8452264/206573024-c992b165-b975-4550-81ed-ac95dc23379e.png">

**Comment by wrg20** [comment]
@magjarvis - do you have a few links you could share.

**Comment by magjarvis** [comment]
https://mcb.illinois.edu/academics/phd-programs/apply-our-phd-program

https://unihigh2022.web.illinois.edu/about-uni

https://dev.mcb.web.illinois.edu/academics/undergraduate-programs/major-neuroscience

@wrg20 let me know if you need access to the backend, I can give you admin access to our mcb dev site

**Comment by wrg20** [comment]
I see the problem.  
![image](https://user-images.githubusercontent.com/1544079/206740050-0682b23f-6d93-4661-bc06-74a4aa04a756.png)

**Comment by wrg20** [comment]
Looks like your blocks in the subtheme have LAS in the ID so this javascript ID is not being targeted.  May need to change it from an ID to generic block class instead.

**Comment by wrg20** [comment]
you could add it to your subtheme like this (whatever the ID is of the page title) in the meantime
![image](https://user-images.githubusercontent.com/1544079/206740436-70881feb-9548-4bef-8639-59cd7c97915b.png)

**Comment by wrg20** [comment]
![image](https://user-images.githubusercontent.com/1544079/206740577-40fc96a1-6323-48c1-bc06-6320035696d3.png)

**Comment by wrg20** [comment]
![image](https://user-images.githubusercontent.com/1544079/206741195-31d49591-50c4-43aa-bea9-07e290589069.png)

**Comment by wrg20** [comment]
I also see in the image above PhD Programs is a non link...when the 2.14 toolkit JS and CSS is applied the spacing will be fixed

**Comment by magjarvis** [comment]
That was it! Thank you!
