### ISSUE TITLE
Swap out bootstrap5 pager with toolkit pager

### ISSUE THREAD

**Issue by trubach** [ATLAS-Illinois/Illinois-Framework-Theme#884]
The bootstrap5 theme's built-in pager needs to be replaced with the Illinois toolkit pager

The bootstrap5 theme has a pager template file at themes/contrib/bootstrap5/templates/navigation/pager.html.twig

A new pager.html.twig template needs to be created in the illinois_framework_theme that uses the Illinois toolkit pager. Documentation can be found at: https://help.toolkit.illinois.edu/component/pagination/

An example of the bootstrap5 pager can be seen at the bottom of the page at https://drupal-sandbox.webtheme.illinois.edu/

![image](https://user-images.githubusercontent.com/56594946/213232666-85010c0b-4203-4e67-9614-c729f8f59a10.png)

**Comment by nhjohnstone** [comment]
@trubach I was not able to get the toolkit pager to work, so I went with overriding bootstrap styles. let me know if this is ok. thanks!

<img width="778" alt="Screenshot 2023-01-20 at 2 54 10 PM" src="https://user-images.githubusercontent.com/97181257/213803400-487cbd60-d3c5-4daa-b25f-4b44c70f3635.png">

**Comment by trubach** [comment]
The toolkit pager needs to be updated to get it to work with Drupal. Once the issue at web-illinois/toolkit#419 is fixed, we can incorporate it into our theme.

**Comment by trubach** [comment]
@nhjohnstone - There is a workaround that we can implement using JS. Matt put together a CodePen on how we can modify the pager number at https://codepen.io/il-toolkit/pen/bGmmEob

Could you work on adding the pager template that uses the toolkit pager and also include that JS?

**Comment by trubach** [comment]
After looking at the toolkit pager, there's not a clear way to include additional URL parameters, such as "?page=1&keyword=tests". Until we can figure out a way around that, we can match the style of the toolkit.
