### ISSUE TITLE
Configure Metatags module for twitter and open graph

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#886]

**Comment by trubach** [comment]
@wrg20 - Does web-illinois/illinois_framework_core#94 resolve this issue? If so, can you close this one?

**Comment by wrg20** [comment]
Installing the meta tag open graph module allowed us to configure the open graph meta tags that twitter uses for displaying images/descriptions of news/page nodes.
