### ISSUE TITLE
Spotlight Family - Detail page

### ISSUE THREAD

**Issue by nbaxley-uiuc** [ATLAS-Illinois/Illinois-Framework-Theme#89]
- [ ] Needs to include sidebar region/menu

![image](https://user-images.githubusercontent.com/62560479/118193690-c48bc180-b40d-11eb-9a42-d8dfb7c6b65d.png)
https://app.zeplin.io/project/6083082b532b4d1e0f670e65/screen/609d9e91cf4a296a4d1c8959

**Comment by robgasc** [comment]
The basic version is now committed, still waiting on the menu to be added for a complete match.
