### ISSUE TITLE
Spotlight Family - List page

### ISSUE THREAD

**Issue by nbaxley-uiuc** [ATLAS-Illinois/Illinois-Framework-Theme#90]
- [x] Float the image to the left of the Title, Summary, and Read More link
- [x] Make the Read more link into a button using the campus il-button class ([see below](https://github.com/web-illinois/illinois_framework_theme/issues/90#issuecomment-930512807))

![image](https://user-images.githubusercontent.com/62560479/118193895-16344c00-b40e-11eb-9e8e-ff8c8dd872ab.png)
https://app.zeplin.io/project/6083082b532b4d1e0f670e65/screen/609d9e91580f376d26a40f3c

**Comment by robgasc** [comment]
A basic version is now committed.

**Comment by nbaxley-uiuc** [comment]
The campus button class is described here (https://github.com/web-illinois/toolkit/wiki/Button).  I'd recommend using both the il-button and il-blue classes

**Comment by robgasc** [comment]
Pushed these changes. Pull request should be good to go. No config changes needed.
