### ISSUE TITLE
Spotlight Family - Card Slider Block

### ISSUE THREAD

**Issue by nbaxley-uiuc** [ATLAS-Illinois/Illinois-Framework-Theme#92]
![image](https://user-images.githubusercontent.com/62560479/118194055-5a275100-b40e-11eb-87cb-1ac93bbe048d.png)
https://app.zeplin.io/project/6083082b532b4d1e0f670e65/screen/609d9e915d24696b00645ae7

**Comment by nbaxley-uiuc** [comment]
- Need to use a more portrait oriented image style.
- Can reuse the illinois_framework_theme/templates/paragraphs/paragraph-bbtemplate.html with renamed fields
- Might look for Slick Slider or some other slider library.  No preferences from Bill
- JS can be included in the moduel and attached to the TWIG files.

**Comment by magjarvis** [comment]
Duplicate. Resolved with #932
