### ISSUE TITLE
Home page intro paragraph type

### ISSUE THREAD

**Issue by magjarvis** [ATLAS-Illinois/Illinois-Framework-Theme#96]

**Comment by mwllr** [comment]
Need to format for the gray background. 

Currently looks like: 
![Screen Shot 2021-06-16 at 12 52 49 PM](https://user-images.githubusercontent.com/54747669/122268747-0f33aa00-cea2-11eb-92cf-a0b62573f3a1.png)

Needs to have blue text and button should be blue background as default and white in hoverfocus. 
![Screen Shot 2021-06-16 at 12 54 12 PM](https://user-images.githubusercontent.com/54747669/122268797-207cb680-cea2-11eb-995b-c01f372316c7.png)

**Comment by mwllr** [comment]
Need to change up white background option for large and small text.

Currently looks like: 
![Screen Shot 2021-06-16 at 12 52 47 PM](https://user-images.githubusercontent.com/54747669/122269435-d21be780-cea2-11eb-936b-4a826a6afdc9.png)


Needs to be:
gray text, blue button with orange hover/focus.
![Screen Shot 2021-06-16 at 12 59 30 PM](https://user-images.githubusercontent.com/54747669/122269380-c0d2db00-cea2-11eb-9f86-7bb52abacb93.png)

**Comment by lizshalley** [comment]
- [x] thumbprint is cut off on mobile
- [x] button alignment on mobile should match text/title

![Test - Page Intro  Animal Sciences  University of Illinois](https://user-images.githubusercontent.com/8646013/124162863-949f8880-da64-11eb-8a16-28760688dfae.jpeg)

**Comment by mwllr** [comment]
- [x] Can we get the buttons to align without the extra space left/right also? Above example - button should align right with "."
- [x] Also want to change the text on white background to be blue. My apologies for changing this one. Just doesn't look right.
- [x] On mobile, just center all content and buttons regardless of left/right/center.

**Comment by mwllr** [comment]
@magjarvis  - ready for your magic please.

**Comment by mwllr** [comment]
small text:

- [ ] change line-height to 2.125rem
- [ ] padding above small text: 60px
- [ ] padding below small text: 75px
- [ ] padding left and right of small text needs to match main header as it shrinks down. Shouldn't touch sides.

![Screen Shot 2021-08-10 at 11 42 27 AM](https://user-images.githubusercontent.com/54747669/128904941-44062975-0309-445c-8d81-afc676647501.png)
