### ISSUE TITLE
List Collection paragraph

### ISSUE THREAD

**Issue by magjarvis** [ATLAS-Illinois/Illinois-Framework-Theme#98]

**Comment by mwllr** [comment]
Add field for spacing before paragraph: no, small, med, lg, xlg..
See Call to Action Narrow for example already added.

**Comment by lizshalley** [comment]
Add title and subtitle options for paragraph section.

**Comment by lizshalley** [comment]
looks okay on sample list collection page when images are used, but on page with no image, text wraps for some reason.

[https://staging.ansc.illinois.edu/testing/test-list-collection](![Screen Shot 2021-07-02 at 9 48 28 AM](https://user-images.githubusercontent.com/8646013/124292141-e0146e00-db1a-11eb-9976-c3f49e43663c.png))

[https://staging.ansc.illinois.edu/animal-sciences-extension](![Screen Shot 2021-07-02 at 9 48 08 AM](https://user-images.githubusercontent.com/8646013/124292264-00dcc380-db1b-11eb-9bbd-f98b3c1a3522.png)
)

**Comment by lizshalley** [comment]
on mobile, width for text should match image.

![Test - List Collection  Animal Sciences  University of Illinois](https://user-images.githubusercontent.com/8646013/124292590-5c0eb600-db1b-11eb-8c8a-ae51ddadcf64.jpeg)

**Comment by lizshalley** [comment]
on mobile, when image isn't used, text gets cut off.

![Animal Sciences Extension  Animal Sciences  University of Illinois](https://user-images.githubusercontent.com/8646013/124292719-82ccec80-db1b-11eb-823f-57a6c566f83c.jpeg)

**Comment by magjarvis** [comment]
Changes pushed to git:
- added field for spacing
- added title and subtitle options on paragraph
- fixed alignment issues with text
- added mobile styles

Needs review:
- styling for paragraph title and subtitle

**Comment by magjarvis** [comment]
Updated text/image alignment. Updated image style.

**Comment by mwllr** [comment]
image style needs to not be square - Maggie may have already fixed ;)

![Screen Shot 2021-07-09 at 3 45 53 PM](https://user-images.githubusercontent.com/54747669/125134325-d8ca0300-e0cc-11eb-819a-6b9cf6247c8a.png)
![Screen Shot 2021-07-09 at 3 45 40 PM](https://user-images.githubusercontent.com/54747669/125134336-dbc4f380-e0cc-11eb-9d17-ce93c627cf8f.png)

**Comment by lizshalley** [comment]
tighten up spacing between items with no image: [https://staging.ansc.illinois.edu/about/what-we-do-why-it-matters
](https://staging.ansc.illinois.edu/about/what-we-do-why-it-matters)

![Screen Shot 2021-07-12 at 9 58 48 AM](https://user-images.githubusercontent.com/8646013/125310284-0e9eff80-e2f8-11eb-9953-9416ca79de95.png)

**Comment by mwllr** [comment]
List Collection uses on staging: https://staging.ansc.illinois.edu/about/animal-sciences-ambassadors
https://staging.ansc.illinois.edu/student-life/student-organizations

**Comment by mwllr** [comment]
- [x] need to be able to format a button in the body section.
- [x] use white as first background instead of gray.

**Comment by mwllr** [comment]
- [ ] entries that don't use images should use the entire width (see last 3 ambassadors - the text block can be wider.)
- [ ] photos are squished next to side nav.
